# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.user_config_image_dto import UserConfigImageDto

class TestUserConfigImageDto(unittest.TestCase):
    """UserConfigImageDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserConfigImageDto:
        """Test UserConfigImageDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserConfigImageDto`
        """
        model = UserConfigImageDto()
        if include_optional:
            return UserConfigImageDto(
                fullsize = immich_sdk.models.user_config_generated_fullsize_image_dto.UserConfigGeneratedFullsizeImageDto(
                    enabled = True, ),
                preview = immich_sdk.models.user_config_generated_image_dto.UserConfigGeneratedImageDto(
                    size = 1, ),
                thumbnail = immich_sdk.models.user_config_generated_image_dto.UserConfigGeneratedImageDto(
                    size = 1, )
            )
        else:
            return UserConfigImageDto(
                fullsize = immich_sdk.models.user_config_generated_fullsize_image_dto.UserConfigGeneratedFullsizeImageDto(
                    enabled = True, ),
                preview = immich_sdk.models.user_config_generated_image_dto.UserConfigGeneratedImageDto(
                    size = 1, ),
                thumbnail = immich_sdk.models.user_config_generated_image_dto.UserConfigGeneratedImageDto(
                    size = 1, ),
        )
        """

    def testUserConfigImageDto(self):
        """Test UserConfigImageDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
