# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.album_response_dto import AlbumResponseDto

class TestAlbumResponseDto(unittest.TestCase):
    """AlbumResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AlbumResponseDto:
        """Test AlbumResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AlbumResponseDto`
        """
        model = AlbumResponseDto()
        if include_optional:
            return AlbumResponseDto(
                album_name = '',
                album_thumbnail_asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                album_users = [
                    immich_sdk.models.album_user_response_dto.AlbumUserResponseDto(
                        role = 'editor', 
                        user = immich_sdk.models.user_response_dto.UserResponseDto(
                            avatar_color = 'primary', 
                            email = '', 
                            id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                            name = '', 
                            profile_changed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            profile_image_path = '', ), )
                    ],
                asset_count = 0,
                contributor_counts = [
                    immich_sdk.models.contributor_count_response_dto.ContributorCountResponseDto(
                        asset_count = 0, 
                        user_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', )
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                description = '',
                end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                has_shared_link = True,
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                is_activity_enabled = True,
                last_modified_asset_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                order = 'asc',
                shared = True,
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return AlbumResponseDto(
                album_name = '',
                album_thumbnail_asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                album_users = [
                    immich_sdk.models.album_user_response_dto.AlbumUserResponseDto(
                        role = 'editor', 
                        user = immich_sdk.models.user_response_dto.UserResponseDto(
                            avatar_color = 'primary', 
                            email = '', 
                            id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                            name = '', 
                            profile_changed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            profile_image_path = '', ), )
                    ],
                asset_count = 0,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                description = '',
                has_shared_link = True,
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                is_activity_enabled = True,
                shared = True,
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testAlbumResponseDto(self):
        """Test AlbumResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
