# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.stacks_api import StacksApi


class TestStacksApi(unittest.TestCase):
    """StacksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StacksApi()

    def tearDown(self) -> None:
        pass

    def test_create_stack(self) -> None:
        """Test case for create_stack

        Create a stack
        """
        pass

    def test_delete_stack(self) -> None:
        """Test case for delete_stack

        Delete a stack
        """
        pass

    def test_delete_stacks(self) -> None:
        """Test case for delete_stacks

        Delete stacks
        """
        pass

    def test_get_stack(self) -> None:
        """Test case for get_stack

        Retrieve a stack
        """
        pass

    def test_remove_asset_from_stack(self) -> None:
        """Test case for remove_asset_from_stack

        Remove an asset from a stack
        """
        pass

    def test_search_stacks(self) -> None:
        """Test case for search_stacks

        Retrieve stacks
        """
        pass

    def test_update_stack(self) -> None:
        """Test case for update_stack

        Update a stack
        """
        pass


if __name__ == '__main__':
    unittest.main()
