# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.database_backups_admin_api import DatabaseBackupsAdminApi


class TestDatabaseBackupsAdminApi(unittest.TestCase):
    """DatabaseBackupsAdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DatabaseBackupsAdminApi()

    def tearDown(self) -> None:
        pass

    def test_delete_database_backup(self) -> None:
        """Test case for delete_database_backup

        Delete database backup
        """
        pass

    def test_download_database_backup(self) -> None:
        """Test case for download_database_backup

        Download database backup
        """
        pass

    def test_list_database_backups(self) -> None:
        """Test case for list_database_backups

        List database backups
        """
        pass

    def test_start_database_restore_flow(self) -> None:
        """Test case for start_database_restore_flow

        Start database backup restore flow
        """
        pass

    def test_upload_database_backup(self) -> None:
        """Test case for upload_database_backup

        Upload database backup
        """
        pass


if __name__ == '__main__':
    unittest.main()
