# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.tags_api import TagsApi


class TestTagsApi(unittest.TestCase):
    """TagsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TagsApi()

    def tearDown(self) -> None:
        pass

    def test_bulk_tag_assets(self) -> None:
        """Test case for bulk_tag_assets

        Tag assets
        """
        pass

    def test_create_tag(self) -> None:
        """Test case for create_tag

        Create a tag
        """
        pass

    def test_delete_tag(self) -> None:
        """Test case for delete_tag

        Delete a tag
        """
        pass

    def test_get_all_tags(self) -> None:
        """Test case for get_all_tags

        Retrieve tags
        """
        pass

    def test_get_tag_by_id(self) -> None:
        """Test case for get_tag_by_id

        Retrieve a tag
        """
        pass

    def test_tag_assets(self) -> None:
        """Test case for tag_assets

        Tag assets
        """
        pass

    def test_untag_assets(self) -> None:
        """Test case for untag_assets

        Untag assets
        """
        pass

    def test_update_tag(self) -> None:
        """Test case for update_tag

        Update a tag
        """
        pass

    def test_upsert_tags(self) -> None:
        """Test case for upsert_tags

        Upsert tags
        """
        pass


if __name__ == '__main__':
    unittest.main()
