# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.sync_asset_face_v2 import SyncAssetFaceV2

class TestSyncAssetFaceV2(unittest.TestCase):
    """SyncAssetFaceV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncAssetFaceV2:
        """Test SyncAssetFaceV2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncAssetFaceV2`
        """
        model = SyncAssetFaceV2()
        if include_optional:
            return SyncAssetFaceV2(
                asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                bounding_box_x1 = -9007199254740991,
                bounding_box_x2 = -9007199254740991,
                bounding_box_y1 = -9007199254740991,
                bounding_box_y2 = -9007199254740991,
                deleted_at = '2024-01-01T00:00Z',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                image_height = -9007199254740991,
                image_width = -9007199254740991,
                is_visible = True,
                person_id = '',
                source_type = ''
            )
        else:
            return SyncAssetFaceV2(
                asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                bounding_box_x1 = -9007199254740991,
                bounding_box_x2 = -9007199254740991,
                bounding_box_y1 = -9007199254740991,
                bounding_box_y2 = -9007199254740991,
                deleted_at = '2024-01-01T00:00Z',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                image_height = -9007199254740991,
                image_width = -9007199254740991,
                is_visible = True,
                person_id = '',
                source_type = '',
        )
        """

    def testSyncAssetFaceV2(self):
        """Test SyncAssetFaceV2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
