# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.sync_album_to_asset_v1 import SyncAlbumToAssetV1

class TestSyncAlbumToAssetV1(unittest.TestCase):
    """SyncAlbumToAssetV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncAlbumToAssetV1:
        """Test SyncAlbumToAssetV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncAlbumToAssetV1`
        """
        model = SyncAlbumToAssetV1()
        if include_optional:
            return SyncAlbumToAssetV1(
                album_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC'
            )
        else:
            return SyncAlbumToAssetV1(
                album_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
        )
        """

    def testSyncAlbumToAssetV1(self):
        """Test SyncAlbumToAssetV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
