# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.admin_config_image_dto import AdminConfigImageDto

class TestAdminConfigImageDto(unittest.TestCase):
    """AdminConfigImageDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminConfigImageDto:
        """Test AdminConfigImageDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminConfigImageDto`
        """
        model = AdminConfigImageDto()
        if include_optional:
            return AdminConfigImageDto(
                colorspace = 'srgb',
                extract_embedded = True,
                fullsize = immich_sdk.models.admin_config_generated_fullsize_image_dto.AdminConfigGeneratedFullsizeImageDto(
                    enabled = True, 
                    format = 'jpeg', 
                    progressive = True, 
                    quality = 1, ),
                preview = immich_sdk.models.admin_config_generated_image_dto.AdminConfigGeneratedImageDto(
                    format = 'jpeg', 
                    progressive = True, 
                    quality = 1, 
                    size = 1, ),
                thumbnail = immich_sdk.models.admin_config_generated_image_dto.AdminConfigGeneratedImageDto(
                    format = 'jpeg', 
                    progressive = True, 
                    quality = 1, 
                    size = 1, )
            )
        else:
            return AdminConfigImageDto(
                colorspace = 'srgb',
                extract_embedded = True,
                fullsize = immich_sdk.models.admin_config_generated_fullsize_image_dto.AdminConfigGeneratedFullsizeImageDto(
                    enabled = True, 
                    format = 'jpeg', 
                    progressive = True, 
                    quality = 1, ),
                preview = immich_sdk.models.admin_config_generated_image_dto.AdminConfigGeneratedImageDto(
                    format = 'jpeg', 
                    progressive = True, 
                    quality = 1, 
                    size = 1, ),
                thumbnail = immich_sdk.models.admin_config_generated_image_dto.AdminConfigGeneratedImageDto(
                    format = 'jpeg', 
                    progressive = True, 
                    quality = 1, 
                    size = 1, ),
        )
        """

    def testAdminConfigImageDto(self):
        """Test AdminConfigImageDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
