# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.admin_config_library_scan_dto import AdminConfigLibraryScanDto

class TestAdminConfigLibraryScanDto(unittest.TestCase):
    """AdminConfigLibraryScanDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminConfigLibraryScanDto:
        """Test AdminConfigLibraryScanDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminConfigLibraryScanDto`
        """
        model = AdminConfigLibraryScanDto()
        if include_optional:
            return AdminConfigLibraryScanDto(
                cron_expression = '',
                enabled = True
            )
        else:
            return AdminConfigLibraryScanDto(
                cron_expression = '',
                enabled = True,
        )
        """

    def testAdminConfigLibraryScanDto(self):
        """Test AdminConfigLibraryScanDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
