# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.api_key_create_response_dto import ApiKeyCreateResponseDto

class TestApiKeyCreateResponseDto(unittest.TestCase):
    """ApiKeyCreateResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiKeyCreateResponseDto:
        """Test ApiKeyCreateResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiKeyCreateResponseDto`
        """
        model = ApiKeyCreateResponseDto()
        if include_optional:
            return ApiKeyCreateResponseDto(
                api_key = immich_sdk.models.api_key_response_dto.ApiKeyResponseDto(
                    created_at = '2024-01-01T00:00Z', 
                    id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                    name = '', 
                    permissions = [
                        'all'
                        ], 
                    updated_at = '2024-01-01T00:00Z', ),
                created_at = '2024-01-01T00:00Z',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                name = '',
                permissions = [
                    'all'
                    ],
                secret = '',
                updated_at = '2024-01-01T00:00Z'
            )
        else:
            return ApiKeyCreateResponseDto(
                api_key = immich_sdk.models.api_key_response_dto.ApiKeyResponseDto(
                    created_at = '2024-01-01T00:00Z', 
                    id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                    name = '', 
                    permissions = [
                        'all'
                        ], 
                    updated_at = '2024-01-01T00:00Z', ),
                created_at = '2024-01-01T00:00Z',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                name = '',
                permissions = [
                    'all'
                    ],
                secret = '',
                updated_at = '2024-01-01T00:00Z',
        )
        """

    def testApiKeyCreateResponseDto(self):
        """Test ApiKeyCreateResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
