# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.admin_config_trash_dto import AdminConfigTrashDto

class TestAdminConfigTrashDto(unittest.TestCase):
    """AdminConfigTrashDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminConfigTrashDto:
        """Test AdminConfigTrashDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminConfigTrashDto`
        """
        model = AdminConfigTrashDto()
        if include_optional:
            return AdminConfigTrashDto(
                days = 0,
                enabled = True
            )
        else:
            return AdminConfigTrashDto(
                days = 0,
                enabled = True,
        )
        """

    def testAdminConfigTrashDto(self):
        """Test AdminConfigTrashDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
