# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.admin_config_clip_dto import AdminConfigClipDto

class TestAdminConfigClipDto(unittest.TestCase):
    """AdminConfigClipDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminConfigClipDto:
        """Test AdminConfigClipDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminConfigClipDto`
        """
        model = AdminConfigClipDto()
        if include_optional:
            return AdminConfigClipDto(
                enabled = True,
                model_name = ''
            )
        else:
            return AdminConfigClipDto(
                enabled = True,
                model_name = '',
        )
        """

    def testAdminConfigClipDto(self):
        """Test AdminConfigClipDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
