# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.trash_api import TrashApi


class TestTrashApi(unittest.TestCase):
    """TrashApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TrashApi()

    def tearDown(self) -> None:
        pass

    def test_empty_trash(self) -> None:
        """Test case for empty_trash

        Empty trash
        """
        pass

    def test_restore_assets(self) -> None:
        """Test case for restore_assets

        Restore assets
        """
        pass

    def test_restore_trash(self) -> None:
        """Test case for restore_trash

        Restore trash
        """
        pass


if __name__ == '__main__':
    unittest.main()
