# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.user_preferences_response_dto import UserPreferencesResponseDto

class TestUserPreferencesResponseDto(unittest.TestCase):
    """UserPreferencesResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserPreferencesResponseDto:
        """Test UserPreferencesResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserPreferencesResponseDto`
        """
        model = UserPreferencesResponseDto()
        if include_optional:
            return UserPreferencesResponseDto(
                albums = immich_sdk.models.albums_response.AlbumsResponse(
                    default_asset_order = 'asc', ),
                cast = immich_sdk.models.cast_response.CastResponse(
                    g_cast_enabled = True, ),
                download = immich_sdk.models.download_response.DownloadResponse(
                    archive_size = -9007199254740991, 
                    include_embedded_videos = True, ),
                email_notifications = immich_sdk.models.email_notifications_response.EmailNotificationsResponse(
                    album_invite = True, 
                    album_update = True, 
                    enabled = True, ),
                folders = immich_sdk.models.folders_response.FoldersResponse(
                    enabled = True, 
                    sidebar_web = True, ),
                memories = immich_sdk.models.memories_response.MemoriesResponse(
                    duration = -9007199254740991, 
                    enabled = True, 
                    sidebar_web = True, ),
                people = immich_sdk.models.people_response.PeopleResponse(
                    enabled = True, 
                    minimum_faces = 1, 
                    sidebar_web = True, ),
                purchase = immich_sdk.models.purchase_response.PurchaseResponse(
                    hide_buy_button_until = '', 
                    show_support_badge = True, ),
                ratings = immich_sdk.models.ratings_response.RatingsResponse(
                    enabled = True, ),
                recently_added = immich_sdk.models.recently_added_response.RecentlyAddedResponse(
                    sidebar_web = True, ),
                shared_links = immich_sdk.models.shared_links_response.SharedLinksResponse(
                    enabled = True, 
                    sidebar_web = True, ),
                tags = immich_sdk.models.tags_response.TagsResponse(
                    enabled = True, 
                    sidebar_web = True, )
            )
        else:
            return UserPreferencesResponseDto(
                albums = immich_sdk.models.albums_response.AlbumsResponse(
                    default_asset_order = 'asc', ),
                cast = immich_sdk.models.cast_response.CastResponse(
                    g_cast_enabled = True, ),
                download = immich_sdk.models.download_response.DownloadResponse(
                    archive_size = -9007199254740991, 
                    include_embedded_videos = True, ),
                email_notifications = immich_sdk.models.email_notifications_response.EmailNotificationsResponse(
                    album_invite = True, 
                    album_update = True, 
                    enabled = True, ),
                folders = immich_sdk.models.folders_response.FoldersResponse(
                    enabled = True, 
                    sidebar_web = True, ),
                memories = immich_sdk.models.memories_response.MemoriesResponse(
                    duration = -9007199254740991, 
                    enabled = True, 
                    sidebar_web = True, ),
                people = immich_sdk.models.people_response.PeopleResponse(
                    enabled = True, 
                    minimum_faces = 1, 
                    sidebar_web = True, ),
                purchase = immich_sdk.models.purchase_response.PurchaseResponse(
                    hide_buy_button_until = '', 
                    show_support_badge = True, ),
                ratings = immich_sdk.models.ratings_response.RatingsResponse(
                    enabled = True, ),
                recently_added = immich_sdk.models.recently_added_response.RecentlyAddedResponse(
                    sidebar_web = True, ),
                shared_links = immich_sdk.models.shared_links_response.SharedLinksResponse(
                    enabled = True, 
                    sidebar_web = True, ),
                tags = immich_sdk.models.tags_response.TagsResponse(
                    enabled = True, 
                    sidebar_web = True, ),
        )
        """

    def testUserPreferencesResponseDto(self):
        """Test UserPreferencesResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
