# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.admin_config_backups_dto import AdminConfigBackupsDto

class TestAdminConfigBackupsDto(unittest.TestCase):
    """AdminConfigBackupsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminConfigBackupsDto:
        """Test AdminConfigBackupsDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminConfigBackupsDto`
        """
        model = AdminConfigBackupsDto()
        if include_optional:
            return AdminConfigBackupsDto(
                database = immich_sdk.models.admin_config_database_backup_dto.AdminConfigDatabaseBackupDto(
                    cron_expression = '', 
                    enabled = True, 
                    keep_last_amount = 1, )
            )
        else:
            return AdminConfigBackupsDto(
                database = immich_sdk.models.admin_config_database_backup_dto.AdminConfigDatabaseBackupDto(
                    cron_expression = '', 
                    enabled = True, 
                    keep_last_amount = 1, ),
        )
        """

    def testAdminConfigBackupsDto(self):
        """Test AdminConfigBackupsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
