# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.asset_metadata_bulk_delete_dto import AssetMetadataBulkDeleteDto

class TestAssetMetadataBulkDeleteDto(unittest.TestCase):
    """AssetMetadataBulkDeleteDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssetMetadataBulkDeleteDto:
        """Test AssetMetadataBulkDeleteDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssetMetadataBulkDeleteDto`
        """
        model = AssetMetadataBulkDeleteDto()
        if include_optional:
            return AssetMetadataBulkDeleteDto(
                items = [
                    immich_sdk.models.asset_metadata_bulk_delete_item_dto.AssetMetadataBulkDeleteItemDto(
                        asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                        key = '', )
                    ]
            )
        else:
            return AssetMetadataBulkDeleteDto(
                items = [
                    immich_sdk.models.asset_metadata_bulk_delete_item_dto.AssetMetadataBulkDeleteItemDto(
                        asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                        key = '', )
                    ],
        )
        """

    def testAssetMetadataBulkDeleteDto(self):
        """Test AssetMetadataBulkDeleteDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
