# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.workflow_create_dto import WorkflowCreateDto

class TestWorkflowCreateDto(unittest.TestCase):
    """WorkflowCreateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowCreateDto:
        """Test WorkflowCreateDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowCreateDto`
        """
        model = WorkflowCreateDto()
        if include_optional:
            return WorkflowCreateDto(
                description = '',
                enabled = True,
                logging = True,
                name = '',
                steps = [
                    immich_sdk.models.workflow_step_dto.WorkflowStepDto(
                        config = {
                            'key' : null
                            }, 
                        enabled = True, 
                        method = '', )
                    ],
                trigger = 'AssetCreate'
            )
        else:
            return WorkflowCreateDto(
                trigger = 'AssetCreate',
        )
        """

    def testWorkflowCreateDto(self):
        """Test WorkflowCreateDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
