# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.timeline_api import TimelineApi


class TestTimelineApi(unittest.TestCase):
    """TimelineApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TimelineApi()

    def tearDown(self) -> None:
        pass

    def test_get_time_bucket(self) -> None:
        """Test case for get_time_bucket

        Get time bucket
        """
        pass

    def test_get_time_buckets(self) -> None:
        """Test case for get_time_buckets

        Get time buckets
        """
        pass


if __name__ == '__main__':
    unittest.main()
