# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.maintenance_status_response_dto import MaintenanceStatusResponseDto

class TestMaintenanceStatusResponseDto(unittest.TestCase):
    """MaintenanceStatusResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MaintenanceStatusResponseDto:
        """Test MaintenanceStatusResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MaintenanceStatusResponseDto`
        """
        model = MaintenanceStatusResponseDto()
        if include_optional:
            return MaintenanceStatusResponseDto(
                action = 'start',
                active = True,
                error = '',
                progress = -9007199254740991,
                task = ''
            )
        else:
            return MaintenanceStatusResponseDto(
                action = 'start',
                active = True,
        )
        """

    def testMaintenanceStatusResponseDto(self):
        """Test MaintenanceStatusResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
