# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.bulk_id_response_dto import BulkIdResponseDto

class TestBulkIdResponseDto(unittest.TestCase):
    """BulkIdResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkIdResponseDto:
        """Test BulkIdResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkIdResponseDto`
        """
        model = BulkIdResponseDto()
        if include_optional:
            return BulkIdResponseDto(
                error = 'duplicate',
                error_message = '',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                success = True
            )
        else:
            return BulkIdResponseDto(
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                success = True,
        )
        """

    def testBulkIdResponseDto(self):
        """Test BulkIdResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
