# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.user_admin_create_dto import UserAdminCreateDto

class TestUserAdminCreateDto(unittest.TestCase):
    """UserAdminCreateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserAdminCreateDto:
        """Test UserAdminCreateDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserAdminCreateDto`
        """
        model = UserAdminCreateDto()
        if include_optional:
            return UserAdminCreateDto(
                avatar_color = 'primary',
                email = '',
                is_admin = True,
                name = '',
                notify = True,
                password = '',
                pin_code = '123456',
                quota_size_in_bytes = 0,
                should_change_password = True,
                storage_label = ''
            )
        else:
            return UserAdminCreateDto(
                email = '',
                name = '',
                password = '',
        )
        """

    def testUserAdminCreateDto(self):
        """Test UserAdminCreateDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
