# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.release_channel import ReleaseChannel

class TestReleaseChannel(unittest.TestCase):
    """ReleaseChannel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReleaseChannel(self):
        """Test ReleaseChannel"""
        # inst = ReleaseChannel()

if __name__ == '__main__':
    unittest.main()
