# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.public_config_server_dto import PublicConfigServerDto

class TestPublicConfigServerDto(unittest.TestCase):
    """PublicConfigServerDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublicConfigServerDto:
        """Test PublicConfigServerDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublicConfigServerDto`
        """
        model = PublicConfigServerDto()
        if include_optional:
            return PublicConfigServerDto(
                login_page_message = ''
            )
        else:
            return PublicConfigServerDto(
                login_page_message = '',
        )
        """

    def testPublicConfigServerDto(self):
        """Test PublicConfigServerDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
