# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.activity_response_dto import ActivityResponseDto

class TestActivityResponseDto(unittest.TestCase):
    """ActivityResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActivityResponseDto:
        """Test ActivityResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActivityResponseDto`
        """
        model = ActivityResponseDto()
        if include_optional:
            return ActivityResponseDto(
                asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                comment = '',
                created_at = '2024-01-01T00:00Z',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                type = 'comment',
                user = immich_sdk.models.user_response_dto.UserResponseDto(
                    avatar_color = 'primary', 
                    email = '', 
                    id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                    name = '', 
                    profile_changed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    profile_image_path = '', )
            )
        else:
            return ActivityResponseDto(
                asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                created_at = '2024-01-01T00:00Z',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                type = 'comment',
                user = immich_sdk.models.user_response_dto.UserResponseDto(
                    avatar_color = 'primary', 
                    email = '', 
                    id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                    name = '', 
                    profile_changed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    profile_image_path = '', ),
        )
        """

    def testActivityResponseDto(self):
        """Test ActivityResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
