# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.user_config_trash_dto import UserConfigTrashDto

class TestUserConfigTrashDto(unittest.TestCase):
    """UserConfigTrashDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserConfigTrashDto:
        """Test UserConfigTrashDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserConfigTrashDto`
        """
        model = UserConfigTrashDto()
        if include_optional:
            return UserConfigTrashDto(
                days = 0,
                enabled = True
            )
        else:
            return UserConfigTrashDto(
                days = 0,
                enabled = True,
        )
        """

    def testUserConfigTrashDto(self):
        """Test UserConfigTrashDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
