# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.user_admin_response_dto import UserAdminResponseDto

class TestUserAdminResponseDto(unittest.TestCase):
    """UserAdminResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserAdminResponseDto:
        """Test UserAdminResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserAdminResponseDto`
        """
        model = UserAdminResponseDto()
        if include_optional:
            return UserAdminResponseDto(
                avatar_color = 'primary',
                cluster_group_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                created_at = '2024-01-01T00:00Z',
                deleted_at = '2024-01-01T00:00Z',
                email = '',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                is_admin = True,
                license = immich_sdk.models.user_license.UserLicense(
                    activated_at = '2024-01-01T00:00Z', 
                    activation_key = '', 
                    license_key = 'IMCL-Cu2L-C4aW-wWL9-Y864-DZta-GRyy-GFZK-kkp4', ),
                name = '',
                oauth_id = '',
                profile_changed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                profile_image_path = '',
                quota_size_in_bytes = 0,
                quota_usage_in_bytes = 0,
                should_change_password = True,
                status = 'active',
                storage_label = '',
                updated_at = '2024-01-01T00:00Z'
            )
        else:
            return UserAdminResponseDto(
                avatar_color = 'primary',
                cluster_group_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                created_at = '2024-01-01T00:00Z',
                deleted_at = '2024-01-01T00:00Z',
                email = '',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                is_admin = True,
                license = immich_sdk.models.user_license.UserLicense(
                    activated_at = '2024-01-01T00:00Z', 
                    activation_key = '', 
                    license_key = 'IMCL-Cu2L-C4aW-wWL9-Y864-DZta-GRyy-GFZK-kkp4', ),
                name = '',
                oauth_id = '',
                profile_changed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                profile_image_path = '',
                quota_size_in_bytes = 0,
                quota_usage_in_bytes = 0,
                should_change_password = True,
                status = 'active',
                storage_label = '',
                updated_at = '2024-01-01T00:00Z',
        )
        """

    def testUserAdminResponseDto(self):
        """Test UserAdminResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
