# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.asset_order_by import AssetOrderBy

class TestAssetOrderBy(unittest.TestCase):
    """AssetOrderBy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssetOrderBy(self):
        """Test AssetOrderBy"""
        # inst = AssetOrderBy()

if __name__ == '__main__':
    unittest.main()
