# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.admin_config_o_auth_dto import AdminConfigOAuthDto

class TestAdminConfigOAuthDto(unittest.TestCase):
    """AdminConfigOAuthDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminConfigOAuthDto:
        """Test AdminConfigOAuthDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminConfigOAuthDto`
        """
        model = AdminConfigOAuthDto()
        if include_optional:
            return AdminConfigOAuthDto(
                account_management_url = '',
                allow_insecure_requests = True,
                auto_launch = True,
                auto_register = True,
                button_text = '',
                client_id = '',
                client_secret = '',
                default_storage_quota = 0,
                enabled = True,
                end_session_endpoint = '',
                issuer_url = '',
                mobile_override_enabled = True,
                mobile_redirect_uri = '',
                profile_signing_algorithm = '',
                prompt = '',
                role_claim = '',
                scope = '',
                signing_algorithm = '',
                storage_label_claim = '',
                storage_quota_claim = '',
                timeout = 1,
                token_endpoint_auth_method = 'client_secret_post'
            )
        else:
            return AdminConfigOAuthDto(
                allow_insecure_requests = True,
                auto_launch = True,
                auto_register = True,
                button_text = '',
                client_id = '',
                client_secret = '',
                default_storage_quota = 0,
                enabled = True,
                end_session_endpoint = '',
                issuer_url = '',
                mobile_override_enabled = True,
                mobile_redirect_uri = '',
                profile_signing_algorithm = '',
                prompt = '',
                role_claim = '',
                scope = '',
                signing_algorithm = '',
                storage_label_claim = '',
                storage_quota_claim = '',
                timeout = 1,
                token_endpoint_auth_method = 'client_secret_post',
        )
        """

    def testAdminConfigOAuthDto(self):
        """Test AdminConfigOAuthDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
