# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.search_explore_item import SearchExploreItem

class TestSearchExploreItem(unittest.TestCase):
    """SearchExploreItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchExploreItem:
        """Test SearchExploreItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchExploreItem`
        """
        model = SearchExploreItem()
        if include_optional:
            return SearchExploreItem(
                data = immich_sdk.models.asset_response_dto.AssetResponseDto(
                    checksum = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    duplicate_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                    duration = 0, 
                    exif_info = immich_sdk.models.exif_response_dto.ExifResponseDto(
                        city = '', 
                        country = '', 
                        date_time_original = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        description = '', 
                        exif_image_height = 0, 
                        exif_image_width = 0, 
                        exposure_time = '', 
                        f_number = 1.337, 
                        file_size_in_byte = 0, 
                        focal_length = 1.337, 
                        iso = -9007199254740991, 
                        latitude = 1.337, 
                        lens_model = '', 
                        longitude = 1.337, 
                        make = '', 
                        model = '', 
                        modify_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        orientation = '', 
                        projection_type = '', 
                        rating = 1, 
                        state = '', 
                        time_zone = '', ), 
                    file_created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    file_modified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    has_metadata = True, 
                    height = 0, 
                    id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                    is_archived = True, 
                    is_edited = True, 
                    is_favorite = True, 
                    is_offline = True, 
                    is_trashed = True, 
                    library_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                    live_photo_video_id = '', 
                    local_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    original_file_name = '', 
                    original_mime_type = '', 
                    original_path = '', 
                    owner = immich_sdk.models.user_response_dto.UserResponseDto(
                        avatar_color = 'primary', 
                        email = '', 
                        id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                        name = '', 
                        profile_changed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        profile_image_path = '', ), 
                    owner_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                    people = [
                        immich_sdk.models.person_response_dto.PersonResponseDto(
                            birth_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            color = '', 
                            id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                            is_favorite = True, 
                            is_hidden = True, 
                            name = '', 
                            thumbnail_path = '', 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    resized = True, 
                    stack = null, 
                    tags = [
                        immich_sdk.models.tag_response_dto.TagResponseDto(
                            color = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                            name = '', 
                            parent_id = '', 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            value = '', )
                        ], 
                    thumbhash = '', 
                    type = 'IMAGE', 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    visibility = 'archive', 
                    width = 0, ),
                value = ''
            )
        else:
            return SearchExploreItem(
                data = immich_sdk.models.asset_response_dto.AssetResponseDto(
                    checksum = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    duplicate_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                    duration = 0, 
                    exif_info = immich_sdk.models.exif_response_dto.ExifResponseDto(
                        city = '', 
                        country = '', 
                        date_time_original = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        description = '', 
                        exif_image_height = 0, 
                        exif_image_width = 0, 
                        exposure_time = '', 
                        f_number = 1.337, 
                        file_size_in_byte = 0, 
                        focal_length = 1.337, 
                        iso = -9007199254740991, 
                        latitude = 1.337, 
                        lens_model = '', 
                        longitude = 1.337, 
                        make = '', 
                        model = '', 
                        modify_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        orientation = '', 
                        projection_type = '', 
                        rating = 1, 
                        state = '', 
                        time_zone = '', ), 
                    file_created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    file_modified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    has_metadata = True, 
                    height = 0, 
                    id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                    is_archived = True, 
                    is_edited = True, 
                    is_favorite = True, 
                    is_offline = True, 
                    is_trashed = True, 
                    library_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                    live_photo_video_id = '', 
                    local_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    original_file_name = '', 
                    original_mime_type = '', 
                    original_path = '', 
                    owner = immich_sdk.models.user_response_dto.UserResponseDto(
                        avatar_color = 'primary', 
                        email = '', 
                        id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                        name = '', 
                        profile_changed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        profile_image_path = '', ), 
                    owner_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                    people = [
                        immich_sdk.models.person_response_dto.PersonResponseDto(
                            birth_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            color = '', 
                            id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                            is_favorite = True, 
                            is_hidden = True, 
                            name = '', 
                            thumbnail_path = '', 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    resized = True, 
                    stack = null, 
                    tags = [
                        immich_sdk.models.tag_response_dto.TagResponseDto(
                            color = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                            name = '', 
                            parent_id = '', 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            value = '', )
                        ], 
                    thumbhash = '', 
                    type = 'IMAGE', 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    visibility = 'archive', 
                    width = 0, ),
                value = '',
        )
        """

    def testSearchExploreItem(self):
        """Test SearchExploreItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
