# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.assets_api import AssetsApi


class TestAssetsApi(unittest.TestCase):
    """AssetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AssetsApi()

    def tearDown(self) -> None:
        pass

    def test_check_bulk_upload(self) -> None:
        """Test case for check_bulk_upload

        Check bulk upload
        """
        pass

    def test_copy_asset(self) -> None:
        """Test case for copy_asset

        Copy asset
        """
        pass

    def test_delete_asset_metadata(self) -> None:
        """Test case for delete_asset_metadata

        Delete asset metadata by key
        """
        pass

    def test_delete_assets(self) -> None:
        """Test case for delete_assets

        Delete assets
        """
        pass

    def test_delete_bulk_asset_metadata(self) -> None:
        """Test case for delete_bulk_asset_metadata

        Delete asset metadata
        """
        pass

    def test_download_asset(self) -> None:
        """Test case for download_asset

        Download original asset
        """
        pass

    def test_edit_asset(self) -> None:
        """Test case for edit_asset

        Apply edits to an existing asset
        """
        pass

    def test_end_session(self) -> None:
        """Test case for end_session

        End HLS streaming session
        """
        pass

    def test_get_asset_edits(self) -> None:
        """Test case for get_asset_edits

        Retrieve edits for an existing asset
        """
        pass

    def test_get_asset_info(self) -> None:
        """Test case for get_asset_info

        Retrieve an asset
        """
        pass

    def test_get_asset_metadata(self) -> None:
        """Test case for get_asset_metadata

        Get asset metadata
        """
        pass

    def test_get_asset_metadata_by_key(self) -> None:
        """Test case for get_asset_metadata_by_key

        Retrieve asset metadata by key
        """
        pass

    def test_get_asset_ocr(self) -> None:
        """Test case for get_asset_ocr

        Retrieve asset OCR data
        """
        pass

    def test_get_asset_statistics(self) -> None:
        """Test case for get_asset_statistics

        Get asset statistics
        """
        pass

    def test_get_main_playlist(self) -> None:
        """Test case for get_main_playlist

        Get HLS main playlist
        """
        pass

    def test_get_media_playlist(self) -> None:
        """Test case for get_media_playlist

        Get HLS media playlist
        """
        pass

    def test_get_segment(self) -> None:
        """Test case for get_segment

        Get HLS segment or init file
        """
        pass

    def test_play_asset_video(self) -> None:
        """Test case for play_asset_video

        Play asset video
        """
        pass

    def test_remove_asset_edits(self) -> None:
        """Test case for remove_asset_edits

        Remove edits from an existing asset
        """
        pass

    def test_run_asset_jobs(self) -> None:
        """Test case for run_asset_jobs

        Run an asset job
        """
        pass

    def test_update_asset(self) -> None:
        """Test case for update_asset

        Update an asset
        """
        pass

    def test_update_asset_metadata(self) -> None:
        """Test case for update_asset_metadata

        Update asset metadata
        """
        pass

    def test_update_assets(self) -> None:
        """Test case for update_assets

        Update assets
        """
        pass

    def test_update_bulk_asset_metadata(self) -> None:
        """Test case for update_bulk_asset_metadata

        Upsert asset metadata
        """
        pass

    def test_upload_asset(self) -> None:
        """Test case for upload_asset

        Upload asset
        """
        pass

    def test_view_asset(self) -> None:
        """Test case for view_asset

        View asset thumbnail
        """
        pass


if __name__ == '__main__':
    unittest.main()
