# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.partner_update_dto import PartnerUpdateDto

class TestPartnerUpdateDto(unittest.TestCase):
    """PartnerUpdateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PartnerUpdateDto:
        """Test PartnerUpdateDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PartnerUpdateDto`
        """
        model = PartnerUpdateDto()
        if include_optional:
            return PartnerUpdateDto(
                in_timeline = True
            )
        else:
            return PartnerUpdateDto(
                in_timeline = True,
        )
        """

    def testPartnerUpdateDto(self):
        """Test PartnerUpdateDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
