# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.public_config_dto import PublicConfigDto

class TestPublicConfigDto(unittest.TestCase):
    """PublicConfigDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublicConfigDto:
        """Test PublicConfigDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublicConfigDto`
        """
        model = PublicConfigDto()
        if include_optional:
            return PublicConfigDto(
                oauth = immich_sdk.models.public_config_o_auth_dto.PublicConfigOAuthDto(
                    auto_launch = True, 
                    button_text = '', 
                    enabled = True, ),
                password_login = immich_sdk.models.public_config_password_login_dto.PublicConfigPasswordLoginDto(
                    enabled = True, ),
                server = immich_sdk.models.public_config_server_dto.PublicConfigServerDto(
                    login_page_message = '', ),
                theme = immich_sdk.models.public_config_theme_dto.PublicConfigThemeDto(
                    custom_css = '', )
            )
        else:
            return PublicConfigDto(
                oauth = immich_sdk.models.public_config_o_auth_dto.PublicConfigOAuthDto(
                    auto_launch = True, 
                    button_text = '', 
                    enabled = True, ),
                password_login = immich_sdk.models.public_config_password_login_dto.PublicConfigPasswordLoginDto(
                    enabled = True, ),
                server = immich_sdk.models.public_config_server_dto.PublicConfigServerDto(
                    login_page_message = '', ),
                theme = immich_sdk.models.public_config_theme_dto.PublicConfigThemeDto(
                    custom_css = '', ),
        )
        """

    def testPublicConfigDto(self):
        """Test PublicConfigDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
