# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.queue_status_legacy_dto import QueueStatusLegacyDto

class TestQueueStatusLegacyDto(unittest.TestCase):
    """QueueStatusLegacyDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueueStatusLegacyDto:
        """Test QueueStatusLegacyDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueueStatusLegacyDto`
        """
        model = QueueStatusLegacyDto()
        if include_optional:
            return QueueStatusLegacyDto(
                is_active = True,
                is_paused = True
            )
        else:
            return QueueStatusLegacyDto(
                is_active = True,
                is_paused = True,
        )
        """

    def testQueueStatusLegacyDto(self):
        """Test QueueStatusLegacyDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
