# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.admin_config_template_emails_dto import AdminConfigTemplateEmailsDto

class TestAdminConfigTemplateEmailsDto(unittest.TestCase):
    """AdminConfigTemplateEmailsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminConfigTemplateEmailsDto:
        """Test AdminConfigTemplateEmailsDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminConfigTemplateEmailsDto`
        """
        model = AdminConfigTemplateEmailsDto()
        if include_optional:
            return AdminConfigTemplateEmailsDto(
                album_invite_template = '',
                album_update_template = '',
                welcome_template = ''
            )
        else:
            return AdminConfigTemplateEmailsDto(
                album_invite_template = '',
                album_update_template = '',
                welcome_template = '',
        )
        """

    def testAdminConfigTemplateEmailsDto(self):
        """Test AdminConfigTemplateEmailsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
