# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.config_user_api import ConfigUserApi


class TestConfigUserApi(unittest.TestCase):
    """ConfigUserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConfigUserApi()

    def tearDown(self) -> None:
        pass

    def test_get_user_config(self) -> None:
        """Test case for get_user_config

        Get the configuration with user visibility
        """
        pass

    def test_get_user_config_defaults(self) -> None:
        """Test case for get_user_config_defaults

        Get the default configuration with user visibility
        """
        pass


if __name__ == '__main__':
    unittest.main()
