# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.plugin_template_response_dto import PluginTemplateResponseDto

class TestPluginTemplateResponseDto(unittest.TestCase):
    """PluginTemplateResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PluginTemplateResponseDto:
        """Test PluginTemplateResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PluginTemplateResponseDto`
        """
        model = PluginTemplateResponseDto()
        if include_optional:
            return PluginTemplateResponseDto(
                description = '',
                key = '',
                steps = [
                    immich_sdk.models.plugin_template_step_response_dto.PluginTemplateStepResponseDto(
                        config = {
                            'key' : null
                            }, 
                        enabled = True, 
                        method = '', )
                    ],
                title = '',
                trigger = 'AssetCreate',
                ui_hints = [
                    ''
                    ]
            )
        else:
            return PluginTemplateResponseDto(
                description = '',
                key = '',
                steps = [
                    immich_sdk.models.plugin_template_step_response_dto.PluginTemplateStepResponseDto(
                        config = {
                            'key' : null
                            }, 
                        enabled = True, 
                        method = '', )
                    ],
                title = '',
                trigger = 'AssetCreate',
                ui_hints = [
                    ''
                    ],
        )
        """

    def testPluginTemplateResponseDto(self):
        """Test PluginTemplateResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
