# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.admin_config_metadata_dto import AdminConfigMetadataDto

class TestAdminConfigMetadataDto(unittest.TestCase):
    """AdminConfigMetadataDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminConfigMetadataDto:
        """Test AdminConfigMetadataDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminConfigMetadataDto`
        """
        model = AdminConfigMetadataDto()
        if include_optional:
            return AdminConfigMetadataDto(
                faces = immich_sdk.models.admin_config_faces_dto.AdminConfigFacesDto(
                    import = True, )
            )
        else:
            return AdminConfigMetadataDto(
                faces = immich_sdk.models.admin_config_faces_dto.AdminConfigFacesDto(
                    import = True, ),
        )
        """

    def testAdminConfigMetadataDto(self):
        """Test AdminConfigMetadataDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
