# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.sync_asset_v2 import SyncAssetV2

class TestSyncAssetV2(unittest.TestCase):
    """SyncAssetV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncAssetV2:
        """Test SyncAssetV2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncAssetV2`
        """
        model = SyncAssetV2()
        if include_optional:
            return SyncAssetV2(
                checksum = '',
                created_at = '2024-01-01T00:00Z',
                deleted_at = '2024-01-01T00:00Z',
                duration = 0,
                file_created_at = '2024-01-01T00:00Z',
                file_modified_at = '2024-01-01T00:00Z',
                height = -9007199254740991,
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                is_edited = True,
                is_favorite = True,
                library_id = '',
                live_photo_video_id = '',
                local_date_time = '2024-01-01T00:00Z',
                original_file_name = '',
                owner_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                stack_id = '',
                thumbhash = '',
                type = 'IMAGE',
                visibility = 'archive',
                width = -9007199254740991
            )
        else:
            return SyncAssetV2(
                checksum = '',
                created_at = '2024-01-01T00:00Z',
                deleted_at = '2024-01-01T00:00Z',
                duration = 0,
                file_created_at = '2024-01-01T00:00Z',
                file_modified_at = '2024-01-01T00:00Z',
                height = -9007199254740991,
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                is_edited = True,
                is_favorite = True,
                library_id = '',
                live_photo_video_id = '',
                local_date_time = '2024-01-01T00:00Z',
                original_file_name = '',
                owner_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                stack_id = '',
                thumbhash = '',
                type = 'IMAGE',
                visibility = 'archive',
                width = -9007199254740991,
        )
        """

    def testSyncAssetV2(self):
        """Test SyncAssetV2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
