# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.people_api import PeopleApi


class TestPeopleApi(unittest.TestCase):
    """PeopleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PeopleApi()

    def tearDown(self) -> None:
        pass

    def test_create_person(self) -> None:
        """Test case for create_person

        Create a person
        """
        pass

    def test_delete_people(self) -> None:
        """Test case for delete_people

        Delete people
        """
        pass

    def test_delete_person(self) -> None:
        """Test case for delete_person

        Delete person
        """
        pass

    def test_get_all_people(self) -> None:
        """Test case for get_all_people

        Get all people
        """
        pass

    def test_get_person(self) -> None:
        """Test case for get_person

        Get a person
        """
        pass

    def test_get_person_statistics(self) -> None:
        """Test case for get_person_statistics

        Get person statistics
        """
        pass

    def test_get_person_thumbnail(self) -> None:
        """Test case for get_person_thumbnail

        Get person thumbnail
        """
        pass

    def test_merge_person(self) -> None:
        """Test case for merge_person

        Merge people
        """
        pass

    def test_reassign_faces(self) -> None:
        """Test case for reassign_faces

        Reassign faces
        """
        pass

    def test_update_people(self) -> None:
        """Test case for update_people

        Update people
        """
        pass

    def test_update_person(self) -> None:
        """Test case for update_person

        Update person
        """
        pass


if __name__ == '__main__':
    unittest.main()
