# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.admin_config_facial_recognition_dto import AdminConfigFacialRecognitionDto

class TestAdminConfigFacialRecognitionDto(unittest.TestCase):
    """AdminConfigFacialRecognitionDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminConfigFacialRecognitionDto:
        """Test AdminConfigFacialRecognitionDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminConfigFacialRecognitionDto`
        """
        model = AdminConfigFacialRecognitionDto()
        if include_optional:
            return AdminConfigFacialRecognitionDto(
                enabled = True,
                max_distance = 0.1,
                min_faces = 1,
                min_score = 0.1,
                model_name = ''
            )
        else:
            return AdminConfigFacialRecognitionDto(
                enabled = True,
                max_distance = 0.1,
                min_faces = 1,
                min_score = 0.1,
                model_name = '',
        )
        """

    def testAdminConfigFacialRecognitionDto(self):
        """Test AdminConfigFacialRecognitionDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
