# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.user_config_reverse_geocoding_dto import UserConfigReverseGeocodingDto

class TestUserConfigReverseGeocodingDto(unittest.TestCase):
    """UserConfigReverseGeocodingDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserConfigReverseGeocodingDto:
        """Test UserConfigReverseGeocodingDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserConfigReverseGeocodingDto`
        """
        model = UserConfigReverseGeocodingDto()
        if include_optional:
            return UserConfigReverseGeocodingDto(
                enabled = True
            )
        else:
            return UserConfigReverseGeocodingDto(
                enabled = True,
        )
        """

    def testUserConfigReverseGeocodingDto(self):
        """Test UserConfigReverseGeocodingDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
