# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.maintenance_admin_api import MaintenanceAdminApi


class TestMaintenanceAdminApi(unittest.TestCase):
    """MaintenanceAdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MaintenanceAdminApi()

    def tearDown(self) -> None:
        pass

    def test_delete_integrity_report(self) -> None:
        """Test case for delete_integrity_report

        Delete integrity report item
        """
        pass

    def test_detect_prior_install(self) -> None:
        """Test case for detect_prior_install

        Detect existing install
        """
        pass

    def test_get_integrity_report(self) -> None:
        """Test case for get_integrity_report

        Get integrity report by type
        """
        pass

    def test_get_integrity_report_csv(self) -> None:
        """Test case for get_integrity_report_csv

        Export integrity report by type as CSV
        """
        pass

    def test_get_integrity_report_file(self) -> None:
        """Test case for get_integrity_report_file

        Download flagged file
        """
        pass

    def test_get_integrity_report_summary(self) -> None:
        """Test case for get_integrity_report_summary

        Get integrity report summary
        """
        pass

    def test_get_maintenance_status(self) -> None:
        """Test case for get_maintenance_status

        Get maintenance mode status
        """
        pass

    def test_maintenance_login(self) -> None:
        """Test case for maintenance_login

        Log into maintenance mode
        """
        pass

    def test_set_maintenance_mode(self) -> None:
        """Test case for set_maintenance_mode

        Set maintenance mode
        """
        pass


if __name__ == '__main__':
    unittest.main()
