# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.string_pattern_filter import StringPatternFilter

class TestStringPatternFilter(unittest.TestCase):
    """StringPatternFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StringPatternFilter:
        """Test StringPatternFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StringPatternFilter`
        """
        model = StringPatternFilter()
        if include_optional:
            return StringPatternFilter(
                ends_with = '0',
                eq = '',
                var_in = [
                    ''
                    ],
                like = '0',
                ne = '',
                not_in = [
                    ''
                    ],
                not_like = '0',
                starts_with = '0'
            )
        else:
            return StringPatternFilter(
        )
        """

    def testStringPatternFilter(self):
        """Test StringPatternFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
