# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.calendar_heatmap_response_dto import CalendarHeatmapResponseDto

class TestCalendarHeatmapResponseDto(unittest.TestCase):
    """CalendarHeatmapResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CalendarHeatmapResponseDto:
        """Test CalendarHeatmapResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CalendarHeatmapResponseDto`
        """
        model = CalendarHeatmapResponseDto()
        if include_optional:
            return CalendarHeatmapResponseDto(
                var_from = '2024-01-01',
                series = [
                    immich_sdk.models.calendar_heatmap_response_dto_series_inner.CalendarHeatmapResponseDto_series_inner(
                        count = 0, 
                        date = '2024-01-01', )
                    ],
                to = '2024-12-31',
                total_count = 0
            )
        else:
            return CalendarHeatmapResponseDto(
                var_from = '2024-01-01',
                series = [
                    immich_sdk.models.calendar_heatmap_response_dto_series_inner.CalendarHeatmapResponseDto_series_inner(
                        count = 0, 
                        date = '2024-01-01', )
                    ],
                to = '2024-12-31',
                total_count = 0,
        )
        """

    def testCalendarHeatmapResponseDto(self):
        """Test CalendarHeatmapResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
