# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.create_profile_image_response_dto import CreateProfileImageResponseDto

class TestCreateProfileImageResponseDto(unittest.TestCase):
    """CreateProfileImageResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateProfileImageResponseDto:
        """Test CreateProfileImageResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateProfileImageResponseDto`
        """
        model = CreateProfileImageResponseDto()
        if include_optional:
            return CreateProfileImageResponseDto(
                profile_changed_at = '2024-01-01T00:00Z',
                profile_image_path = '',
                user_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC'
            )
        else:
            return CreateProfileImageResponseDto(
                profile_changed_at = '2024-01-01T00:00Z',
                profile_image_path = '',
                user_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
        )
        """

    def testCreateProfileImageResponseDto(self):
        """Test CreateProfileImageResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
