# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.deprecated_api import DeprecatedApi


class TestDeprecatedApi(unittest.TestCase):
    """DeprecatedApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeprecatedApi()

    def tearDown(self) -> None:
        pass

    def test_create_partner_deprecated(self) -> None:
        """Test case for create_partner_deprecated

        Create a partner
        """
        pass

    def test_get_config(self) -> None:
        """Test case for get_config

        Get system configuration
        """
        pass

    def test_get_config_defaults(self) -> None:
        """Test case for get_config_defaults

        Get system configuration defaults
        """
        pass

    def test_get_queues_legacy(self) -> None:
        """Test case for get_queues_legacy

        Retrieve queue counts and status
        """
        pass

    def test_get_server_config(self) -> None:
        """Test case for get_server_config

        Get config
        """
        pass

    def test_get_server_features(self) -> None:
        """Test case for get_server_features

        Get features
        """
        pass

    def test_run_queue_command_legacy(self) -> None:
        """Test case for run_queue_command_legacy

        Run jobs
        """
        pass

    def test_search_large_assets(self) -> None:
        """Test case for search_large_assets

        Search large assets
        """
        pass

    def test_update_api_key(self) -> None:
        """Test case for update_api_key

        Update an API key
        """
        pass

    def test_update_asset(self) -> None:
        """Test case for update_asset

        Update an asset
        """
        pass

    def test_update_assets(self) -> None:
        """Test case for update_assets

        Update assets
        """
        pass

    def test_update_config(self) -> None:
        """Test case for update_config

        Update system configuration
        """
        pass

    def test_update_library(self) -> None:
        """Test case for update_library

        Update a library
        """
        pass

    def test_update_memory(self) -> None:
        """Test case for update_memory

        Update a memory
        """
        pass

    def test_update_my_preferences(self) -> None:
        """Test case for update_my_preferences

        Update my preferences
        """
        pass

    def test_update_my_user(self) -> None:
        """Test case for update_my_user

        Update current user
        """
        pass

    def test_update_person(self) -> None:
        """Test case for update_person

        Update person
        """
        pass

    def test_update_session(self) -> None:
        """Test case for update_session

        Update a session
        """
        pass

    def test_update_stack(self) -> None:
        """Test case for update_stack

        Update a stack
        """
        pass

    def test_update_tag(self) -> None:
        """Test case for update_tag

        Update a tag
        """
        pass

    def test_update_user_admin(self) -> None:
        """Test case for update_user_admin

        Update a user
        """
        pass

    def test_update_user_preferences_admin(self) -> None:
        """Test case for update_user_preferences_admin

        Update user preferences
        """
        pass

    def test_update_workflow(self) -> None:
        """Test case for update_workflow

        Update a workflow
        """
        pass


if __name__ == '__main__':
    unittest.main()
