# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.authentication_admin_api import AuthenticationAdminApi


class TestAuthenticationAdminApi(unittest.TestCase):
    """AuthenticationAdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthenticationAdminApi()

    def tearDown(self) -> None:
        pass

    def test_unlink_all_o_auth_accounts_admin(self) -> None:
        """Test case for unlink_all_o_auth_accounts_admin

        Unlink all OAuth accounts
        """
        pass


if __name__ == '__main__':
    unittest.main()
