# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.server_config_dto import ServerConfigDto

class TestServerConfigDto(unittest.TestCase):
    """ServerConfigDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServerConfigDto:
        """Test ServerConfigDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServerConfigDto`
        """
        model = ServerConfigDto()
        if include_optional:
            return ServerConfigDto(
                external_domain = '',
                is_initialized = True,
                is_onboarded = True,
                login_page_message = '',
                maintenance_mode = True,
                map_dark_style_url = '',
                map_light_style_url = '',
                min_faces = -9007199254740991,
                oauth_account_management_url = '',
                oauth_button_text = '',
                public_users = True,
                trash_days = -9007199254740991,
                user_delete_delay = -9007199254740991
            )
        else:
            return ServerConfigDto(
                external_domain = '',
                is_initialized = True,
                is_onboarded = True,
                login_page_message = '',
                maintenance_mode = True,
                map_dark_style_url = '',
                map_light_style_url = '',
                min_faces = -9007199254740991,
                oauth_button_text = '',
                public_users = True,
                trash_days = -9007199254740991,
                user_delete_delay = -9007199254740991,
        )
        """

    def testServerConfigDto(self):
        """Test ServerConfigDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
