# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.sync_asset_metadata_v1 import SyncAssetMetadataV1

class TestSyncAssetMetadataV1(unittest.TestCase):
    """SyncAssetMetadataV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncAssetMetadataV1:
        """Test SyncAssetMetadataV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncAssetMetadataV1`
        """
        model = SyncAssetMetadataV1()
        if include_optional:
            return SyncAssetMetadataV1(
                asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                key = '',
                value = {
                    'key' : null
                    }
            )
        else:
            return SyncAssetMetadataV1(
                asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                key = '',
                value = {
                    'key' : null
                    },
        )
        """

    def testSyncAssetMetadataV1(self):
        """Test SyncAssetMetadataV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
