# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.api_keys_api import APIKeysApi


class TestAPIKeysApi(unittest.TestCase):
    """APIKeysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = APIKeysApi()

    def tearDown(self) -> None:
        pass

    def test_create_api_key(self) -> None:
        """Test case for create_api_key

        Create an API key
        """
        pass

    def test_delete_api_key(self) -> None:
        """Test case for delete_api_key

        Delete an API key
        """
        pass

    def test_get_api_key(self) -> None:
        """Test case for get_api_key

        Retrieve an API key
        """
        pass

    def test_get_api_keys(self) -> None:
        """Test case for get_api_keys

        List all API keys
        """
        pass

    def test_get_my_api_key(self) -> None:
        """Test case for get_my_api_key

        Retrieve the current API key
        """
        pass

    def test_rotate_api_key(self) -> None:
        """Test case for rotate_api_key

        Rotate an API key
        """
        pass

    def test_update_api_key(self) -> None:
        """Test case for update_api_key

        Update an API key
        """
        pass


if __name__ == '__main__':
    unittest.main()
