# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.admin_config_templates_dto import AdminConfigTemplatesDto

class TestAdminConfigTemplatesDto(unittest.TestCase):
    """AdminConfigTemplatesDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminConfigTemplatesDto:
        """Test AdminConfigTemplatesDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminConfigTemplatesDto`
        """
        model = AdminConfigTemplatesDto()
        if include_optional:
            return AdminConfigTemplatesDto(
                email = immich_sdk.models.admin_config_template_emails_dto.AdminConfigTemplateEmailsDto(
                    album_invite_template = '', 
                    album_update_template = '', 
                    welcome_template = '', )
            )
        else:
            return AdminConfigTemplatesDto(
                email = immich_sdk.models.admin_config_template_emails_dto.AdminConfigTemplateEmailsDto(
                    album_invite_template = '', 
                    album_update_template = '', 
                    welcome_template = '', ),
        )
        """

    def testAdminConfigTemplatesDto(self):
        """Test AdminConfigTemplatesDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
