# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.sync_stack_v1 import SyncStackV1

class TestSyncStackV1(unittest.TestCase):
    """SyncStackV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncStackV1:
        """Test SyncStackV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncStackV1`
        """
        model = SyncStackV1()
        if include_optional:
            return SyncStackV1(
                created_at = '2024-01-01T00:00Z',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                owner_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                primary_asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                updated_at = '2024-01-01T00:00Z'
            )
        else:
            return SyncStackV1(
                created_at = '2024-01-01T00:00Z',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                owner_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                primary_asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                updated_at = '2024-01-01T00:00Z',
        )
        """

    def testSyncStackV1(self):
        """Test SyncStackV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
