# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.search_filter import SearchFilter

class TestSearchFilter(unittest.TestCase):
    """SearchFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchFilter:
        """Test SearchFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchFilter`
        """
        model = SearchFilter()
        if include_optional:
            return SearchFilter(
                album_ids = immich_sdk.models.ids_filter.IdsFilter(
                    all = [
                        '62ECB020-8429-430c-a01F-FCCfeEe150AC'
                        ], 
                    any = [
                        '62ECB020-8429-430c-a01F-FCCfeEe150AC'
                        ], 
                    none = [
                        '62ECB020-8429-430c-a01F-FCCfeEe150AC'
                        ], ),
                checksum = immich_sdk.models.string_filter.StringFilter(
                    eq = '', 
                    in = [
                        ''
                        ], 
                    ne = '', 
                    not_in = [
                        ''
                        ], ),
                city = immich_sdk.models.string_filter_nullable.StringFilterNullable(
                    eq = '', 
                    in = [
                        ''
                        ], 
                    ne = '', 
                    not_in = [
                        ''
                        ], ),
                country = immich_sdk.models.string_filter_nullable.StringFilterNullable(
                    eq = '', 
                    in = [
                        ''
                        ], 
                    ne = '', 
                    not_in = [
                        ''
                        ], ),
                created_at = immich_sdk.models.date_filter.DateFilter(
                    eq = '2024-01-01T00:00Z', 
                    gt = '2024-01-01T00:00Z', 
                    gte = '2024-01-01T00:00Z', 
                    lt = '2024-01-01T00:00Z', 
                    lte = '2024-01-01T00:00Z', 
                    ne = '2024-01-01T00:00Z', ),
                description = immich_sdk.models.string_pattern_filter.StringPatternFilter(
                    ends_with = '0', 
                    eq = '', 
                    in = [
                        ''
                        ], 
                    like = '0', 
                    ne = '', 
                    not_in = [
                        ''
                        ], 
                    not_like = '0', 
                    starts_with = '0', ),
                encoded_video_path = immich_sdk.models.string_filter.StringFilter(
                    eq = '', 
                    in = [
                        ''
                        ], 
                    ne = '', 
                    not_in = [
                        ''
                        ], ),
                file_size_in_bytes = immich_sdk.models.number_filter.NumberFilter(
                    eq = 1.337, 
                    gt = 1.337, 
                    gte = 1.337, 
                    in = [
                        1.337
                        ], 
                    lt = 1.337, 
                    lte = 1.337, 
                    ne = 1.337, 
                    not_in = [
                        1.337
                        ], ),
                has_albums = immich_sdk.models.bool_filter.BoolFilter(
                    eq = True, ),
                has_people = immich_sdk.models.bool_filter.BoolFilter(
                    eq = True, ),
                has_tags = immich_sdk.models.bool_filter.BoolFilter(
                    eq = True, ),
                id = immich_sdk.models.id_filter.IdFilter(
                    eq = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                    ne = '62ECB020-8429-430c-a01F-FCCfeEe150AC', ),
                is_encoded = immich_sdk.models.bool_filter.BoolFilter(
                    eq = True, ),
                is_favorite = immich_sdk.models.bool_filter.BoolFilter(
                    eq = True, ),
                is_motion = immich_sdk.models.bool_filter.BoolFilter(
                    eq = True, ),
                is_offline = immich_sdk.models.bool_filter.BoolFilter(
                    eq = True, ),
                lens_model = immich_sdk.models.string_filter_nullable.StringFilterNullable(
                    eq = '', 
                    in = [
                        ''
                        ], 
                    ne = '', 
                    not_in = [
                        ''
                        ], ),
                library_id = immich_sdk.models.id_filter_nullable.IdFilterNullable(
                    eq = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                    ne = '62ECB020-8429-430c-a01F-FCCfeEe150AC', ),
                make = immich_sdk.models.string_filter_nullable.StringFilterNullable(
                    eq = '', 
                    in = [
                        ''
                        ], 
                    ne = '', 
                    not_in = [
                        ''
                        ], ),
                model = immich_sdk.models.string_filter_nullable.StringFilterNullable(
                    eq = '', 
                    in = [
                        ''
                        ], 
                    ne = '', 
                    not_in = [
                        ''
                        ], ),
                ocr = immich_sdk.models.string_similarity_filter.StringSimilarityFilter(
                    matches = '0', ),
                var_or = [
                    immich_sdk.models.search_filter_branch.SearchFilterBranch(
                        album_ids = immich_sdk.models.ids_filter.IdsFilter(
                            all = [
                                '62ECB020-8429-430c-a01F-FCCfeEe150AC'
                                ], 
                            any = [
                                '62ECB020-8429-430c-a01F-FCCfeEe150AC'
                                ], 
                            none = [
                                '62ECB020-8429-430c-a01F-FCCfeEe150AC'
                                ], ), 
                        checksum = immich_sdk.models.string_filter.StringFilter(
                            eq = '', 
                            in = [
                                ''
                                ], 
                            ne = '', 
                            not_in = [
                                ''
                                ], ), 
                        city = immich_sdk.models.string_filter_nullable.StringFilterNullable(
                            eq = '', 
                            ne = '', ), 
                        country = immich_sdk.models.string_filter_nullable.StringFilterNullable(
                            eq = '', 
                            ne = '', ), 
                        created_at = immich_sdk.models.date_filter.DateFilter(
                            eq = '2024-01-01T00:00Z', 
                            gt = '2024-01-01T00:00Z', 
                            gte = '2024-01-01T00:00Z', 
                            lt = '2024-01-01T00:00Z', 
                            lte = '2024-01-01T00:00Z', 
                            ne = '2024-01-01T00:00Z', ), 
                        description = immich_sdk.models.string_pattern_filter.StringPatternFilter(
                            ends_with = '0', 
                            eq = '', 
                            like = '0', 
                            ne = '', 
                            not_like = '0', 
                            starts_with = '0', ), 
                        encoded_video_path = immich_sdk.models.string_filter.StringFilter(
                            eq = '', 
                            ne = '', ), 
                        file_size_in_bytes = immich_sdk.models.number_filter.NumberFilter(
                            eq = 1.337, 
                            gt = 1.337, 
                            gte = 1.337, 
                            lt = 1.337, 
                            lte = 1.337, 
                            ne = 1.337, ), 
                        has_albums = immich_sdk.models.bool_filter.BoolFilter(
                            eq = True, ), 
                        has_people = immich_sdk.models.bool_filter.BoolFilter(
                            eq = True, ), 
                        has_tags = , 
                        id = immich_sdk.models.id_filter.IdFilter(
                            eq = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                            ne = '62ECB020-8429-430c-a01F-FCCfeEe150AC', ), 
                        is_encoded = , 
                        is_favorite = , 
                        is_motion = , 
                        is_offline = , 
                        lens_model = , 
                        library_id = immich_sdk.models.id_filter_nullable.IdFilterNullable(
                            eq = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                            ne = '62ECB020-8429-430c-a01F-FCCfeEe150AC', ), 
                        make = , 
                        model = , 
                        ocr = immich_sdk.models.string_similarity_filter.StringSimilarityFilter(
                            matches = '0', ), 
                        original_file_name = immich_sdk.models.string_pattern_filter.StringPatternFilter(
                            ends_with = '0', 
                            eq = '', 
                            like = '0', 
                            ne = '', 
                            not_like = '0', 
                            starts_with = '0', ), 
                        original_path = , 
                        person_ids = immich_sdk.models.ids_filter.IdsFilter(), 
                        rating = immich_sdk.models.number_filter_nullable.NumberFilterNullable(
                            eq = 1.337, 
                            gt = 1.337, 
                            gte = 1.337, 
                            lt = 1.337, 
                            lte = 1.337, 
                            ne = 1.337, ), 
                        state = , 
                        tag_ids = , 
                        taken_at = immich_sdk.models.date_filter.DateFilter(
                            eq = '2024-01-01T00:00Z', 
                            gt = '2024-01-01T00:00Z', 
                            gte = '2024-01-01T00:00Z', 
                            lt = '2024-01-01T00:00Z', 
                            lte = '2024-01-01T00:00Z', 
                            ne = '2024-01-01T00:00Z', ), 
                        trashed_at = immich_sdk.models.date_filter_nullable.DateFilterNullable(
                            eq = '2024-01-01T00:00Z', 
                            gt = '2024-01-01T00:00Z', 
                            gte = '2024-01-01T00:00Z', 
                            lt = '2024-01-01T00:00Z', 
                            lte = '2024-01-01T00:00Z', 
                            ne = '2024-01-01T00:00Z', ), 
                        type = immich_sdk.models.enum_filter_asset_type.EnumFilterAssetType(
                            eq = 'IMAGE', 
                            ne = 'IMAGE', ), 
                        updated_at = , 
                        visibility = immich_sdk.models.enum_filter_asset_visibility.EnumFilterAssetVisibility(), )
                    ],
                original_file_name = immich_sdk.models.string_pattern_filter.StringPatternFilter(
                    ends_with = '0', 
                    eq = '', 
                    in = [
                        ''
                        ], 
                    like = '0', 
                    ne = '', 
                    not_in = [
                        ''
                        ], 
                    not_like = '0', 
                    starts_with = '0', ),
                original_path = immich_sdk.models.string_pattern_filter.StringPatternFilter(
                    ends_with = '0', 
                    eq = '', 
                    in = [
                        ''
                        ], 
                    like = '0', 
                    ne = '', 
                    not_in = [
                        ''
                        ], 
                    not_like = '0', 
                    starts_with = '0', ),
                person_ids = immich_sdk.models.ids_filter.IdsFilter(
                    all = [
                        '62ECB020-8429-430c-a01F-FCCfeEe150AC'
                        ], 
                    any = [
                        '62ECB020-8429-430c-a01F-FCCfeEe150AC'
                        ], 
                    none = [
                        '62ECB020-8429-430c-a01F-FCCfeEe150AC'
                        ], ),
                rating = immich_sdk.models.number_filter_nullable.NumberFilterNullable(
                    eq = 1.337, 
                    gt = 1.337, 
                    gte = 1.337, 
                    in = [
                        1.337
                        ], 
                    lt = 1.337, 
                    lte = 1.337, 
                    ne = 1.337, 
                    not_in = [
                        1.337
                        ], ),
                state = immich_sdk.models.string_filter_nullable.StringFilterNullable(
                    eq = '', 
                    in = [
                        ''
                        ], 
                    ne = '', 
                    not_in = [
                        ''
                        ], ),
                tag_ids = immich_sdk.models.ids_filter.IdsFilter(
                    all = [
                        '62ECB020-8429-430c-a01F-FCCfeEe150AC'
                        ], 
                    any = [
                        '62ECB020-8429-430c-a01F-FCCfeEe150AC'
                        ], 
                    none = [
                        '62ECB020-8429-430c-a01F-FCCfeEe150AC'
                        ], ),
                taken_at = immich_sdk.models.date_filter.DateFilter(
                    eq = '2024-01-01T00:00Z', 
                    gt = '2024-01-01T00:00Z', 
                    gte = '2024-01-01T00:00Z', 
                    lt = '2024-01-01T00:00Z', 
                    lte = '2024-01-01T00:00Z', 
                    ne = '2024-01-01T00:00Z', ),
                trashed_at = immich_sdk.models.date_filter_nullable.DateFilterNullable(
                    eq = '2024-01-01T00:00Z', 
                    gt = '2024-01-01T00:00Z', 
                    gte = '2024-01-01T00:00Z', 
                    lt = '2024-01-01T00:00Z', 
                    lte = '2024-01-01T00:00Z', 
                    ne = '2024-01-01T00:00Z', ),
                type = immich_sdk.models.enum_filter_asset_type.EnumFilterAssetType(
                    eq = 'IMAGE', 
                    in = [
                        'IMAGE'
                        ], 
                    ne = 'IMAGE', 
                    not_in = [
                        'IMAGE'
                        ], ),
                updated_at = immich_sdk.models.date_filter.DateFilter(
                    eq = '2024-01-01T00:00Z', 
                    gt = '2024-01-01T00:00Z', 
                    gte = '2024-01-01T00:00Z', 
                    lt = '2024-01-01T00:00Z', 
                    lte = '2024-01-01T00:00Z', 
                    ne = '2024-01-01T00:00Z', ),
                visibility = immich_sdk.models.enum_filter_asset_visibility.EnumFilterAssetVisibility(
                    eq = 'archive', 
                    in = [
                        'archive'
                        ], 
                    ne = 'archive', 
                    not_in = [
                        'archive'
                        ], )
            )
        else:
            return SearchFilter(
        )
        """

    def testSearchFilter(self):
        """Test SearchFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
