# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.maintenance_detect_install_storage_folder_dto import MaintenanceDetectInstallStorageFolderDto

class TestMaintenanceDetectInstallStorageFolderDto(unittest.TestCase):
    """MaintenanceDetectInstallStorageFolderDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MaintenanceDetectInstallStorageFolderDto:
        """Test MaintenanceDetectInstallStorageFolderDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MaintenanceDetectInstallStorageFolderDto`
        """
        model = MaintenanceDetectInstallStorageFolderDto()
        if include_optional:
            return MaintenanceDetectInstallStorageFolderDto(
                files = -9007199254740991,
                folder = 'encoded-video',
                readable = True,
                writable = True
            )
        else:
            return MaintenanceDetectInstallStorageFolderDto(
                files = -9007199254740991,
                folder = 'encoded-video',
                readable = True,
                writable = True,
        )
        """

    def testMaintenanceDetectInstallStorageFolderDto(self):
        """Test MaintenanceDetectInstallStorageFolderDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
