# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.map_api import MapApi


class TestMapApi(unittest.TestCase):
    """MapApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MapApi()

    def tearDown(self) -> None:
        pass

    def test_get_map_markers(self) -> None:
        """Test case for get_map_markers

        Retrieve map markers
        """
        pass

    def test_reverse_geocode(self) -> None:
        """Test case for reverse_geocode

        Reverse geocode coordinates
        """
        pass


if __name__ == '__main__':
    unittest.main()
