# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.date_filter_nullable import DateFilterNullable

class TestDateFilterNullable(unittest.TestCase):
    """DateFilterNullable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DateFilterNullable:
        """Test DateFilterNullable
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DateFilterNullable`
        """
        model = DateFilterNullable()
        if include_optional:
            return DateFilterNullable(
                eq = '2024-01-01T00:00Z',
                gt = '2024-01-01T00:00Z',
                gte = '2024-01-01T00:00Z',
                lt = '2024-01-01T00:00Z',
                lte = '2024-01-01T00:00Z',
                ne = '2024-01-01T00:00Z'
            )
        else:
            return DateFilterNullable(
        )
        """

    def testDateFilterNullable(self):
        """Test DateFilterNullable"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
