# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.update_asset_dto import UpdateAssetDto

class TestUpdateAssetDto(unittest.TestCase):
    """UpdateAssetDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateAssetDto:
        """Test UpdateAssetDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateAssetDto`
        """
        model = UpdateAssetDto()
        if include_optional:
            return UpdateAssetDto(
                date_time_original = '',
                description = '',
                is_favorite = True,
                latitude = -90,
                live_photo_video_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                longitude = -180,
                rating = -1,
                visibility = 'archive'
            )
        else:
            return UpdateAssetDto(
        )
        """

    def testUpdateAssetDto(self):
        """Test UpdateAssetDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
