# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.sync_album_v1 import SyncAlbumV1

class TestSyncAlbumV1(unittest.TestCase):
    """SyncAlbumV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncAlbumV1:
        """Test SyncAlbumV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncAlbumV1`
        """
        model = SyncAlbumV1()
        if include_optional:
            return SyncAlbumV1(
                created_at = '2024-01-01T00:00Z',
                description = '',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                is_activity_enabled = True,
                name = '',
                order = 'asc',
                owner_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                thumbnail_asset_id = '',
                updated_at = '2024-01-01T00:00Z'
            )
        else:
            return SyncAlbumV1(
                created_at = '2024-01-01T00:00Z',
                description = '',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                is_activity_enabled = True,
                name = '',
                order = 'asc',
                owner_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                thumbnail_asset_id = '',
                updated_at = '2024-01-01T00:00Z',
        )
        """

    def testSyncAlbumV1(self):
        """Test SyncAlbumV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
