# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.user_config_theme_dto import UserConfigThemeDto

class TestUserConfigThemeDto(unittest.TestCase):
    """UserConfigThemeDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserConfigThemeDto:
        """Test UserConfigThemeDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserConfigThemeDto`
        """
        model = UserConfigThemeDto()
        if include_optional:
            return UserConfigThemeDto(
                custom_css = ''
            )
        else:
            return UserConfigThemeDto(
                custom_css = '',
        )
        """

    def testUserConfigThemeDto(self):
        """Test UserConfigThemeDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
