# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.users_admin_api import UsersAdminApi


class TestUsersAdminApi(unittest.TestCase):
    """UsersAdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersAdminApi()

    def tearDown(self) -> None:
        pass

    def test_create_user_admin(self) -> None:
        """Test case for create_user_admin

        Create a user
        """
        pass

    def test_delete_user_admin(self) -> None:
        """Test case for delete_user_admin

        Delete a user
        """
        pass

    def test_get_user_admin(self) -> None:
        """Test case for get_user_admin

        Retrieve a user
        """
        pass

    def test_get_user_calendar_heatmap_admin(self) -> None:
        """Test case for get_user_calendar_heatmap_admin

        Retrieve calendar heatmap activity
        """
        pass

    def test_get_user_preferences_admin(self) -> None:
        """Test case for get_user_preferences_admin

        Retrieve user preferences
        """
        pass

    def test_get_user_sessions_admin(self) -> None:
        """Test case for get_user_sessions_admin

        Retrieve user sessions
        """
        pass

    def test_get_user_statistics_admin(self) -> None:
        """Test case for get_user_statistics_admin

        Retrieve user statistics
        """
        pass

    def test_restore_user_admin(self) -> None:
        """Test case for restore_user_admin

        Restore a deleted user
        """
        pass

    def test_search_users_admin(self) -> None:
        """Test case for search_users_admin

        Search users
        """
        pass

    def test_update_user_admin(self) -> None:
        """Test case for update_user_admin

        Update a user
        """
        pass

    def test_update_user_preferences_admin(self) -> None:
        """Test case for update_user_preferences_admin

        Update user preferences
        """
        pass


if __name__ == '__main__':
    unittest.main()
