# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.admin_config_job_dto import AdminConfigJobDto

class TestAdminConfigJobDto(unittest.TestCase):
    """AdminConfigJobDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminConfigJobDto:
        """Test AdminConfigJobDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminConfigJobDto`
        """
        model = AdminConfigJobDto()
        if include_optional:
            return AdminConfigJobDto(
                background_task = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                editor = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                face_detection = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                integrity_check = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                library = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                metadata_extraction = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                migration = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                notifications = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                ocr = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                search = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                sidecar = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                smart_search = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                thumbnail_generation = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                video_conversion = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                workflow = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, )
            )
        else:
            return AdminConfigJobDto(
                background_task = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                editor = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                face_detection = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                integrity_check = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                library = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                metadata_extraction = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                migration = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                notifications = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                ocr = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                search = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                sidecar = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                smart_search = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                thumbnail_generation = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                video_conversion = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
                workflow = immich_sdk.models.admin_config_job_settings_dto.AdminConfigJobSettingsDto(
                    concurrency = 1, ),
        )
        """

    def testAdminConfigJobDto(self):
        """Test AdminConfigJobDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
