# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.plugin_response_dto import PluginResponseDto

class TestPluginResponseDto(unittest.TestCase):
    """PluginResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PluginResponseDto:
        """Test PluginResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PluginResponseDto`
        """
        model = PluginResponseDto()
        if include_optional:
            return PluginResponseDto(
                author = '',
                created_at = '',
                description = '',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                methods = [
                    immich_sdk.models.plugin_method_response_dto.PluginMethodResponseDto(
                        description = '', 
                        host_functions = True, 
                        key = '', 
                        name = '', 
                        schema = immich_sdk.models.schema.schema(), 
                        title = '', 
                        types = [
                            'AssetV1'
                            ], 
                        ui_hints = [
                            ''
                            ], )
                    ],
                name = '',
                title = '',
                updated_at = '',
                version = ''
            )
        else:
            return PluginResponseDto(
                author = '',
                created_at = '',
                description = '',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                methods = [
                    immich_sdk.models.plugin_method_response_dto.PluginMethodResponseDto(
                        description = '', 
                        host_functions = True, 
                        key = '', 
                        name = '', 
                        schema = immich_sdk.models.schema.schema(), 
                        title = '', 
                        types = [
                            'AssetV1'
                            ], 
                        ui_hints = [
                            ''
                            ], )
                    ],
                name = '',
                title = '',
                updated_at = '',
                version = '',
        )
        """

    def testPluginResponseDto(self):
        """Test PluginResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
