# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.search_order import SearchOrder

class TestSearchOrder(unittest.TestCase):
    """SearchOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchOrder:
        """Test SearchOrder
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchOrder`
        """
        model = SearchOrder()
        if include_optional:
            return SearchOrder(
                direction = 'asc',
                var_field = 'fileCreatedAt'
            )
        else:
            return SearchOrder(
        )
        """

    def testSearchOrder(self):
        """Test SearchOrder"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
