# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.system_config_api import SystemConfigApi


class TestSystemConfigApi(unittest.TestCase):
    """SystemConfigApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SystemConfigApi()

    def tearDown(self) -> None:
        pass

    def test_get_config(self) -> None:
        """Test case for get_config

        Get system configuration
        """
        pass

    def test_get_config_defaults(self) -> None:
        """Test case for get_config_defaults

        Get system configuration defaults
        """
        pass

    def test_get_storage_template_options(self) -> None:
        """Test case for get_storage_template_options

        Get storage template options
        """
        pass

    def test_update_config(self) -> None:
        """Test case for update_config

        Update system configuration
        """
        pass


if __name__ == '__main__':
    unittest.main()
