# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.library_response_dto import LibraryResponseDto

class TestLibraryResponseDto(unittest.TestCase):
    """LibraryResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LibraryResponseDto:
        """Test LibraryResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LibraryResponseDto`
        """
        model = LibraryResponseDto()
        if include_optional:
            return LibraryResponseDto(
                asset_count = -9007199254740991,
                created_at = '2024-01-01T00:00Z',
                exclusion_patterns = [
                    ''
                    ],
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                import_paths = [
                    ''
                    ],
                name = '',
                owner_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                refreshed_at = '2024-01-01T00:00Z',
                updated_at = '2024-01-01T00:00Z'
            )
        else:
            return LibraryResponseDto(
                asset_count = -9007199254740991,
                created_at = '2024-01-01T00:00Z',
                exclusion_patterns = [
                    ''
                    ],
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                import_paths = [
                    ''
                    ],
                name = '',
                owner_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                refreshed_at = '2024-01-01T00:00Z',
                updated_at = '2024-01-01T00:00Z',
        )
        """

    def testLibraryResponseDto(self):
        """Test LibraryResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
