# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.queue_job_status import QueueJobStatus

class TestQueueJobStatus(unittest.TestCase):
    """QueueJobStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueueJobStatus(self):
        """Test QueueJobStatus"""
        # inst = QueueJobStatus()

if __name__ == '__main__':
    unittest.main()
