# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.search_api import SearchApi


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SearchApi()

    def tearDown(self) -> None:
        pass

    def test_get_assets_by_city(self) -> None:
        """Test case for get_assets_by_city

        Retrieve assets by city
        """
        pass

    def test_get_explore_data(self) -> None:
        """Test case for get_explore_data

        Retrieve explore data
        """
        pass

    def test_get_search_suggestions(self) -> None:
        """Test case for get_search_suggestions

        Retrieve search suggestions
        """
        pass

    def test_search_asset_statistics(self) -> None:
        """Test case for search_asset_statistics

        Search asset statistics
        """
        pass

    def test_search_assets(self) -> None:
        """Test case for search_assets

        Search assets by metadata
        """
        pass

    def test_search_large_assets(self) -> None:
        """Test case for search_large_assets

        Search large assets
        """
        pass

    def test_search_person(self) -> None:
        """Test case for search_person

        Search people
        """
        pass

    def test_search_places(self) -> None:
        """Test case for search_places

        Search places
        """
        pass

    def test_search_random(self) -> None:
        """Test case for search_random

        Search random assets
        """
        pass

    def test_search_smart(self) -> None:
        """Test case for search_smart

        Smart asset search
        """
        pass


if __name__ == '__main__':
    unittest.main()
