# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.admin_config_smtp_dto import AdminConfigSmtpDto

class TestAdminConfigSmtpDto(unittest.TestCase):
    """AdminConfigSmtpDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminConfigSmtpDto:
        """Test AdminConfigSmtpDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminConfigSmtpDto`
        """
        model = AdminConfigSmtpDto()
        if include_optional:
            return AdminConfigSmtpDto(
                enabled = True,
                var_from = '',
                reply_to = '',
                transport = immich_sdk.models.admin_config_smtp_transport_dto.AdminConfigSmtpTransportDto(
                    host = '', 
                    ignore_cert = True, 
                    password = '', 
                    port = 0, 
                    secure = True, 
                    username = '', )
            )
        else:
            return AdminConfigSmtpDto(
                enabled = True,
                var_from = '',
                reply_to = '',
                transport = immich_sdk.models.admin_config_smtp_transport_dto.AdminConfigSmtpTransportDto(
                    host = '', 
                    ignore_cert = True, 
                    password = '', 
                    port = 0, 
                    secure = True, 
                    username = '', ),
        )
        """

    def testAdminConfigSmtpDto(self):
        """Test AdminConfigSmtpDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
