# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.sync_memory_v1 import SyncMemoryV1

class TestSyncMemoryV1(unittest.TestCase):
    """SyncMemoryV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncMemoryV1:
        """Test SyncMemoryV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncMemoryV1`
        """
        model = SyncMemoryV1()
        if include_optional:
            return SyncMemoryV1(
                created_at = '2024-01-01T00:00Z',
                data = {
                    'key' : null
                    },
                deleted_at = '2024-01-01T00:00Z',
                hide_at = '2024-01-01T00:00Z',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                is_saved = True,
                memory_at = '2024-01-01T00:00Z',
                owner_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                seen_at = '2024-01-01T00:00Z',
                show_at = '2024-01-01T00:00Z',
                type = 'on_this_day',
                updated_at = '2024-01-01T00:00Z'
            )
        else:
            return SyncMemoryV1(
                created_at = '2024-01-01T00:00Z',
                data = {
                    'key' : null
                    },
                deleted_at = '2024-01-01T00:00Z',
                hide_at = '2024-01-01T00:00Z',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                is_saved = True,
                memory_at = '2024-01-01T00:00Z',
                owner_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                seen_at = '2024-01-01T00:00Z',
                show_at = '2024-01-01T00:00Z',
                type = 'on_this_day',
                updated_at = '2024-01-01T00:00Z',
        )
        """

    def testSyncMemoryV1(self):
        """Test SyncMemoryV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
