# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.admin_config_generated_fullsize_image_dto import AdminConfigGeneratedFullsizeImageDto

class TestAdminConfigGeneratedFullsizeImageDto(unittest.TestCase):
    """AdminConfigGeneratedFullsizeImageDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminConfigGeneratedFullsizeImageDto:
        """Test AdminConfigGeneratedFullsizeImageDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminConfigGeneratedFullsizeImageDto`
        """
        model = AdminConfigGeneratedFullsizeImageDto()
        if include_optional:
            return AdminConfigGeneratedFullsizeImageDto(
                enabled = True,
                format = 'jpeg',
                progressive = True,
                quality = 1
            )
        else:
            return AdminConfigGeneratedFullsizeImageDto(
                enabled = True,
                format = 'jpeg',
                quality = 1,
        )
        """

    def testAdminConfigGeneratedFullsizeImageDto(self):
        """Test AdminConfigGeneratedFullsizeImageDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
