# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.queues_response_legacy_dto import QueuesResponseLegacyDto

class TestQueuesResponseLegacyDto(unittest.TestCase):
    """QueuesResponseLegacyDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueuesResponseLegacyDto:
        """Test QueuesResponseLegacyDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueuesResponseLegacyDto`
        """
        model = QueuesResponseLegacyDto()
        if include_optional:
            return QueuesResponseLegacyDto(
                background_task = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                backup_database = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                duplicate_detection = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                editor = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                face_detection = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                facial_recognition = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                integrity_check = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                library = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                metadata_extraction = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                migration = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                notifications = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                ocr = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                search = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                sidecar = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                smart_search = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                storage_template_migration = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                thumbnail_generation = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                video_conversion = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                workflow = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), )
            )
        else:
            return QueuesResponseLegacyDto(
                background_task = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                backup_database = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                duplicate_detection = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                editor = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                face_detection = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                facial_recognition = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                integrity_check = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                library = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                metadata_extraction = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                migration = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                notifications = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                ocr = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                search = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                sidecar = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                smart_search = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                storage_template_migration = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                thumbnail_generation = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                video_conversion = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
                workflow = immich_sdk.models.queue_response_legacy_dto.QueueResponseLegacyDto(
                    job_counts = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                        active = -9007199254740991, 
                        completed = -9007199254740991, 
                        delayed = -9007199254740991, 
                        failed = -9007199254740991, 
                        paused = -9007199254740991, 
                        waiting = -9007199254740991, ), 
                    queue_status = immich_sdk.models.queue_status_legacy_dto.QueueStatusLegacyDto(
                        is_active = True, 
                        is_paused = True, ), ),
        )
        """

    def testQueuesResponseLegacyDto(self):
        """Test QueuesResponseLegacyDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
