# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.workflow_log_entry_dto import WorkflowLogEntryDto

class TestWorkflowLogEntryDto(unittest.TestCase):
    """WorkflowLogEntryDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowLogEntryDto:
        """Test WorkflowLogEntryDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowLogEntryDto`
        """
        model = WorkflowLogEntryDto()
        if include_optional:
            return WorkflowLogEntryDto(
                at = '2024-01-01T00:00Z',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                last_step = immich_sdk.models.workflow_log_entry_dto_last_step.WorkflowLogEntryDto_lastStep(
                    index = 0, 
                    method = '', ),
                result = 'completed',
                trigger_data_id = 'ffffffff-ffff-ffff-ffff-ffffffffffff'
            )
        else:
            return WorkflowLogEntryDto(
                at = '2024-01-01T00:00Z',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                result = 'completed',
        )
        """

    def testWorkflowLogEntryDto(self):
        """Test WorkflowLogEntryDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
