# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.sync_auth_user_v1 import SyncAuthUserV1

class TestSyncAuthUserV1(unittest.TestCase):
    """SyncAuthUserV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncAuthUserV1:
        """Test SyncAuthUserV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncAuthUserV1`
        """
        model = SyncAuthUserV1()
        if include_optional:
            return SyncAuthUserV1(
                avatar_color = 'primary',
                deleted_at = '2024-01-01T00:00Z',
                email = '',
                has_profile_image = True,
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                is_admin = True,
                name = '',
                oauth_id = '',
                pin_code = '',
                profile_changed_at = '2024-01-01T00:00Z',
                quota_size_in_bytes = -9007199254740991,
                quota_usage_in_bytes = -9007199254740991,
                storage_label = ''
            )
        else:
            return SyncAuthUserV1(
                deleted_at = '2024-01-01T00:00Z',
                email = '',
                has_profile_image = True,
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                is_admin = True,
                name = '',
                oauth_id = '',
                pin_code = '',
                profile_changed_at = '2024-01-01T00:00Z',
                quota_size_in_bytes = -9007199254740991,
                quota_usage_in_bytes = -9007199254740991,
                storage_label = '',
        )
        """

    def testSyncAuthUserV1(self):
        """Test SyncAuthUserV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
