# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.system_metadata_api import SystemMetadataApi


class TestSystemMetadataApi(unittest.TestCase):
    """SystemMetadataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SystemMetadataApi()

    def tearDown(self) -> None:
        pass

    def test_get_admin_onboarding(self) -> None:
        """Test case for get_admin_onboarding

        Retrieve admin onboarding
        """
        pass

    def test_get_reverse_geocoding_state(self) -> None:
        """Test case for get_reverse_geocoding_state

        Retrieve reverse geocoding state
        """
        pass

    def test_get_version_check_state(self) -> None:
        """Test case for get_version_check_state

        Retrieve version check state
        """
        pass

    def test_update_admin_onboarding(self) -> None:
        """Test case for update_admin_onboarding

        Update admin onboarding
        """
        pass


if __name__ == '__main__':
    unittest.main()
