# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.sync_person_v1 import SyncPersonV1

class TestSyncPersonV1(unittest.TestCase):
    """SyncPersonV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncPersonV1:
        """Test SyncPersonV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncPersonV1`
        """
        model = SyncPersonV1()
        if include_optional:
            return SyncPersonV1(
                birth_date = '2024-01-01T00:00Z',
                color = '',
                created_at = '2024-01-01T00:00Z',
                face_asset_id = '',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                is_favorite = True,
                is_hidden = True,
                name = '',
                owner_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                updated_at = '2024-01-01T00:00Z'
            )
        else:
            return SyncPersonV1(
                birth_date = '2024-01-01T00:00Z',
                color = '',
                created_at = '2024-01-01T00:00Z',
                face_asset_id = '',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                is_favorite = True,
                is_hidden = True,
                name = '',
                owner_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                updated_at = '2024-01-01T00:00Z',
        )
        """

    def testSyncPersonV1(self):
        """Test SyncPersonV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
