# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.sync_user_v1 import SyncUserV1

class TestSyncUserV1(unittest.TestCase):
    """SyncUserV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncUserV1:
        """Test SyncUserV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncUserV1`
        """
        model = SyncUserV1()
        if include_optional:
            return SyncUserV1(
                avatar_color = 'primary',
                deleted_at = '2024-01-01T00:00Z',
                email = '',
                has_profile_image = True,
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                name = '',
                profile_changed_at = '2024-01-01T00:00Z'
            )
        else:
            return SyncUserV1(
                deleted_at = '2024-01-01T00:00Z',
                email = '',
                has_profile_image = True,
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                name = '',
                profile_changed_at = '2024-01-01T00:00Z',
        )
        """

    def testSyncUserV1(self):
        """Test SyncUserV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
