# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.faces_api import FacesApi


class TestFacesApi(unittest.TestCase):
    """FacesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FacesApi()

    def tearDown(self) -> None:
        pass

    def test_create_face(self) -> None:
        """Test case for create_face

        Create a face
        """
        pass

    def test_delete_face(self) -> None:
        """Test case for delete_face

        Delete a face
        """
        pass

    def test_get_faces(self) -> None:
        """Test case for get_faces

        Retrieve faces for asset
        """
        pass

    def test_reassign_faces_by_id(self) -> None:
        """Test case for reassign_faces_by_id

        Re-assign a face to another person
        """
        pass


if __name__ == '__main__':
    unittest.main()
