# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.asset_ocr_response_dto import AssetOcrResponseDto

class TestAssetOcrResponseDto(unittest.TestCase):
    """AssetOcrResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssetOcrResponseDto:
        """Test AssetOcrResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssetOcrResponseDto`
        """
        model = AssetOcrResponseDto()
        if include_optional:
            return AssetOcrResponseDto(
                asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                box_score = 1.337,
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                text = '',
                text_score = 1.337,
                x1 = 1.337,
                x2 = 1.337,
                x3 = 1.337,
                x4 = 1.337,
                y1 = 1.337,
                y2 = 1.337,
                y3 = 1.337,
                y4 = 1.337
            )
        else:
            return AssetOcrResponseDto(
                asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                box_score = 1.337,
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                text = '',
                text_score = 1.337,
                x1 = 1.337,
                x2 = 1.337,
                x3 = 1.337,
                x4 = 1.337,
                y1 = 1.337,
                y2 = 1.337,
                y3 = 1.337,
                y4 = 1.337,
        )
        """

    def testAssetOcrResponseDto(self):
        """Test AssetOcrResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
