# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.plugins_api import PluginsApi


class TestPluginsApi(unittest.TestCase):
    """PluginsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PluginsApi()

    def tearDown(self) -> None:
        pass

    def test_get_plugin(self) -> None:
        """Test case for get_plugin

        Retrieve a plugin
        """
        pass

    def test_search_plugin_methods(self) -> None:
        """Test case for search_plugin_methods

        Retrieve plugin methods
        """
        pass

    def test_search_plugin_templates(self) -> None:
        """Test case for search_plugin_templates

        Retrieve workflow templates
        """
        pass

    def test_search_plugins(self) -> None:
        """Test case for search_plugins

        List all plugins
        """
        pass


if __name__ == '__main__':
    unittest.main()
