# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.albums_api import AlbumsApi


class TestAlbumsApi(unittest.TestCase):
    """AlbumsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AlbumsApi()

    def tearDown(self) -> None:
        pass

    def test_add_assets_to_album(self) -> None:
        """Test case for add_assets_to_album

        Add assets to an album
        """
        pass

    def test_add_assets_to_albums(self) -> None:
        """Test case for add_assets_to_albums

        Add assets to albums
        """
        pass

    def test_add_users_to_album(self) -> None:
        """Test case for add_users_to_album

        Share album with users
        """
        pass

    def test_create_album(self) -> None:
        """Test case for create_album

        Create an album
        """
        pass

    def test_delete_album(self) -> None:
        """Test case for delete_album

        Delete an album
        """
        pass

    def test_get_album_info(self) -> None:
        """Test case for get_album_info

        Retrieve an album
        """
        pass

    def test_get_album_map_markers(self) -> None:
        """Test case for get_album_map_markers

        Retrieve album map markers
        """
        pass

    def test_get_album_statistics(self) -> None:
        """Test case for get_album_statistics

        Retrieve album statistics
        """
        pass

    def test_get_all_albums(self) -> None:
        """Test case for get_all_albums

        List all albums
        """
        pass

    def test_remove_asset_from_album(self) -> None:
        """Test case for remove_asset_from_album

        Remove assets from an album
        """
        pass

    def test_remove_user_from_album(self) -> None:
        """Test case for remove_user_from_album

        Remove user from album
        """
        pass

    def test_update_album_info(self) -> None:
        """Test case for update_album_info

        Update an album
        """
        pass

    def test_update_album_user(self) -> None:
        """Test case for update_album_user

        Update user role
        """
        pass


if __name__ == '__main__':
    unittest.main()
