# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.search_response_dto import SearchResponseDto

class TestSearchResponseDto(unittest.TestCase):
    """SearchResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchResponseDto:
        """Test SearchResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchResponseDto`
        """
        model = SearchResponseDto()
        if include_optional:
            return SearchResponseDto(
                albums = immich_sdk.models.search_album_response_dto.SearchAlbumResponseDto(
                    count = 0, 
                    facets = [
                        immich_sdk.models.search_facet_response_dto.SearchFacetResponseDto(
                            counts = [
                                immich_sdk.models.search_facet_count_response_dto.SearchFacetCountResponseDto(
                                    count = 0, 
                                    value = '', )
                                ], 
                            field_name = '', )
                        ], 
                    items = [
                        immich_sdk.models.album_response_dto.AlbumResponseDto(
                            album_name = '', 
                            album_thumbnail_asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                            album_users = [
                                immich_sdk.models.album_user_response_dto.AlbumUserResponseDto(
                                    role = 'editor', 
                                    user = immich_sdk.models.user_response_dto.UserResponseDto(
                                        avatar_color = 'primary', 
                                        email = '', 
                                        id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                                        name = '', 
                                        profile_changed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        profile_image_path = '', ), )
                                ], 
                            asset_count = 0, 
                            contributor_counts = [
                                immich_sdk.models.contributor_count_response_dto.ContributorCountResponseDto(
                                    asset_count = 0, 
                                    user_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', )
                                ], 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            description = '', 
                            end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            has_shared_link = True, 
                            id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                            is_activity_enabled = True, 
                            last_modified_asset_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            order = 'asc', 
                            shared = True, 
                            start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    total = 0, ),
                assets = immich_sdk.models.search_asset_response_dto.SearchAssetResponseDto(
                    count = 0, 
                    facets = [
                        immich_sdk.models.search_facet_response_dto.SearchFacetResponseDto(
                            counts = [
                                immich_sdk.models.search_facet_count_response_dto.SearchFacetCountResponseDto(
                                    count = 0, 
                                    value = '', )
                                ], 
                            field_name = '', )
                        ], 
                    items = [
                        immich_sdk.models.asset_response_dto.AssetResponseDto(
                            checksum = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            duplicate_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                            duration = 0, 
                            exif_info = immich_sdk.models.exif_response_dto.ExifResponseDto(
                                city = '', 
                                country = '', 
                                date_time_original = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                description = '', 
                                exif_image_height = 0, 
                                exif_image_width = 0, 
                                exposure_time = '', 
                                f_number = 1.337, 
                                file_size_in_byte = 0, 
                                focal_length = 1.337, 
                                iso = -9007199254740991, 
                                latitude = 1.337, 
                                lens_model = '', 
                                longitude = 1.337, 
                                make = '', 
                                model = '', 
                                modify_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                orientation = '', 
                                projection_type = '', 
                                rating = 1, 
                                state = '', 
                                time_zone = '', ), 
                            file_created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            file_modified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            has_metadata = True, 
                            height = 0, 
                            id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                            is_archived = True, 
                            is_edited = True, 
                            is_favorite = True, 
                            is_offline = True, 
                            is_trashed = True, 
                            library_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                            live_photo_video_id = '', 
                            local_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            original_file_name = '', 
                            original_mime_type = '', 
                            original_path = '', 
                            owner = immich_sdk.models.user_response_dto.UserResponseDto(
                                avatar_color = 'primary', 
                                email = '', 
                                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                                name = '', 
                                profile_changed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                profile_image_path = '', ), 
                            owner_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                            people = [
                                immich_sdk.models.person_response_dto.PersonResponseDto(
                                    birth_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                    color = '', 
                                    id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                                    is_favorite = True, 
                                    is_hidden = True, 
                                    name = '', 
                                    thumbnail_path = '', 
                                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                ], 
                            resized = True, 
                            stack = null, 
                            tags = [
                                immich_sdk.models.tag_response_dto.TagResponseDto(
                                    color = '', 
                                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                                    name = '', 
                                    parent_id = '', 
                                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    value = '', )
                                ], 
                            thumbhash = '', 
                            type = 'IMAGE', 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            visibility = 'archive', 
                            width = 0, )
                        ], 
                    next_cursor = '', 
                    next_page = '', 
                    total = 0, )
            )
        else:
            return SearchResponseDto(
                albums = immich_sdk.models.search_album_response_dto.SearchAlbumResponseDto(
                    count = 0, 
                    facets = [
                        immich_sdk.models.search_facet_response_dto.SearchFacetResponseDto(
                            counts = [
                                immich_sdk.models.search_facet_count_response_dto.SearchFacetCountResponseDto(
                                    count = 0, 
                                    value = '', )
                                ], 
                            field_name = '', )
                        ], 
                    items = [
                        immich_sdk.models.album_response_dto.AlbumResponseDto(
                            album_name = '', 
                            album_thumbnail_asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                            album_users = [
                                immich_sdk.models.album_user_response_dto.AlbumUserResponseDto(
                                    role = 'editor', 
                                    user = immich_sdk.models.user_response_dto.UserResponseDto(
                                        avatar_color = 'primary', 
                                        email = '', 
                                        id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                                        name = '', 
                                        profile_changed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        profile_image_path = '', ), )
                                ], 
                            asset_count = 0, 
                            contributor_counts = [
                                immich_sdk.models.contributor_count_response_dto.ContributorCountResponseDto(
                                    asset_count = 0, 
                                    user_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', )
                                ], 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            description = '', 
                            end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            has_shared_link = True, 
                            id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                            is_activity_enabled = True, 
                            last_modified_asset_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            order = 'asc', 
                            shared = True, 
                            start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    total = 0, ),
                assets = immich_sdk.models.search_asset_response_dto.SearchAssetResponseDto(
                    count = 0, 
                    facets = [
                        immich_sdk.models.search_facet_response_dto.SearchFacetResponseDto(
                            counts = [
                                immich_sdk.models.search_facet_count_response_dto.SearchFacetCountResponseDto(
                                    count = 0, 
                                    value = '', )
                                ], 
                            field_name = '', )
                        ], 
                    items = [
                        immich_sdk.models.asset_response_dto.AssetResponseDto(
                            checksum = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            duplicate_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                            duration = 0, 
                            exif_info = immich_sdk.models.exif_response_dto.ExifResponseDto(
                                city = '', 
                                country = '', 
                                date_time_original = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                description = '', 
                                exif_image_height = 0, 
                                exif_image_width = 0, 
                                exposure_time = '', 
                                f_number = 1.337, 
                                file_size_in_byte = 0, 
                                focal_length = 1.337, 
                                iso = -9007199254740991, 
                                latitude = 1.337, 
                                lens_model = '', 
                                longitude = 1.337, 
                                make = '', 
                                model = '', 
                                modify_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                orientation = '', 
                                projection_type = '', 
                                rating = 1, 
                                state = '', 
                                time_zone = '', ), 
                            file_created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            file_modified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            has_metadata = True, 
                            height = 0, 
                            id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                            is_archived = True, 
                            is_edited = True, 
                            is_favorite = True, 
                            is_offline = True, 
                            is_trashed = True, 
                            library_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                            live_photo_video_id = '', 
                            local_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            original_file_name = '', 
                            original_mime_type = '', 
                            original_path = '', 
                            owner = immich_sdk.models.user_response_dto.UserResponseDto(
                                avatar_color = 'primary', 
                                email = '', 
                                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                                name = '', 
                                profile_changed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                profile_image_path = '', ), 
                            owner_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                            people = [
                                immich_sdk.models.person_response_dto.PersonResponseDto(
                                    birth_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                    color = '', 
                                    id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                                    is_favorite = True, 
                                    is_hidden = True, 
                                    name = '', 
                                    thumbnail_path = '', 
                                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                ], 
                            resized = True, 
                            stack = null, 
                            tags = [
                                immich_sdk.models.tag_response_dto.TagResponseDto(
                                    color = '', 
                                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                                    name = '', 
                                    parent_id = '', 
                                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    value = '', )
                                ], 
                            thumbhash = '', 
                            type = 'IMAGE', 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            visibility = 'archive', 
                            width = 0, )
                        ], 
                    next_cursor = '', 
                    next_page = '', 
                    total = 0, ),
        )
        """

    def testSearchResponseDto(self):
        """Test SearchResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
