# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.download_archive_dto import DownloadArchiveDto

class TestDownloadArchiveDto(unittest.TestCase):
    """DownloadArchiveDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DownloadArchiveDto:
        """Test DownloadArchiveDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DownloadArchiveDto`
        """
        model = DownloadArchiveDto()
        if include_optional:
            return DownloadArchiveDto(
                archive_name = '',
                asset_ids = [
                    '62ECB020-8429-430c-a01F-FCCfeEe150AC'
                    ],
                edited = True
            )
        else:
            return DownloadArchiveDto(
                asset_ids = [
                    '62ECB020-8429-430c-a01F-FCCfeEe150AC'
                    ],
        )
        """

    def testDownloadArchiveDto(self):
        """Test DownloadArchiveDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
