# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.onboarding_response_dto import OnboardingResponseDto

class TestOnboardingResponseDto(unittest.TestCase):
    """OnboardingResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OnboardingResponseDto:
        """Test OnboardingResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OnboardingResponseDto`
        """
        model = OnboardingResponseDto()
        if include_optional:
            return OnboardingResponseDto(
                is_onboarded = True
            )
        else:
            return OnboardingResponseDto(
                is_onboarded = True,
        )
        """

    def testOnboardingResponseDto(self):
        """Test OnboardingResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
