# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.memory_update_dto import MemoryUpdateDto

class TestMemoryUpdateDto(unittest.TestCase):
    """MemoryUpdateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MemoryUpdateDto:
        """Test MemoryUpdateDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MemoryUpdateDto`
        """
        model = MemoryUpdateDto()
        if include_optional:
            return MemoryUpdateDto(
                is_saved = True,
                memory_at = '2024-01-01T00:00Z',
                seen_at = '2024-01-01T00:00Z'
            )
        else:
            return MemoryUpdateDto(
        )
        """

    def testMemoryUpdateDto(self):
        """Test MemoryUpdateDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
