# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.asset_files_api import AssetFilesApi


class TestAssetFilesApi(unittest.TestCase):
    """AssetFilesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AssetFilesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_asset_file(self) -> None:
        """Test case for delete_asset_file

        Delete an asset file
        """
        pass

    def test_download_asset_file(self) -> None:
        """Test case for download_asset_file

        Download an asset file
        """
        pass

    def test_get_asset_file(self) -> None:
        """Test case for get_asset_file

        Retrieve an asset file
        """
        pass

    def test_search_asset_files(self) -> None:
        """Test case for search_asset_files

        Search asset files
        """
        pass


if __name__ == '__main__':
    unittest.main()
