# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.memories_response import MemoriesResponse

class TestMemoriesResponse(unittest.TestCase):
    """MemoriesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MemoriesResponse:
        """Test MemoriesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MemoriesResponse`
        """
        model = MemoriesResponse()
        if include_optional:
            return MemoriesResponse(
                duration = -9007199254740991,
                enabled = True,
                sidebar_web = True
            )
        else:
            return MemoriesResponse(
                duration = -9007199254740991,
                enabled = True,
                sidebar_web = True,
        )
        """

    def testMemoriesResponse(self):
        """Test MemoriesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
