# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.admin_config_integrity_checks_dto import AdminConfigIntegrityChecksDto

class TestAdminConfigIntegrityChecksDto(unittest.TestCase):
    """AdminConfigIntegrityChecksDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminConfigIntegrityChecksDto:
        """Test AdminConfigIntegrityChecksDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminConfigIntegrityChecksDto`
        """
        model = AdminConfigIntegrityChecksDto()
        if include_optional:
            return AdminConfigIntegrityChecksDto(
                checksum_files = immich_sdk.models.admin_config_integrity_checksum_job_dto.AdminConfigIntegrityChecksumJobDto(
                    cron_expression = '', 
                    enabled = True, 
                    percentage_limit = 0, 
                    time_limit = 0, ),
                missing_files = immich_sdk.models.admin_config_integrity_job_dto.AdminConfigIntegrityJobDto(
                    cron_expression = '', 
                    enabled = True, ),
                untracked_files = immich_sdk.models.admin_config_integrity_job_dto.AdminConfigIntegrityJobDto(
                    cron_expression = '', 
                    enabled = True, )
            )
        else:
            return AdminConfigIntegrityChecksDto(
                checksum_files = immich_sdk.models.admin_config_integrity_checksum_job_dto.AdminConfigIntegrityChecksumJobDto(
                    cron_expression = '', 
                    enabled = True, 
                    percentage_limit = 0, 
                    time_limit = 0, ),
                missing_files = immich_sdk.models.admin_config_integrity_job_dto.AdminConfigIntegrityJobDto(
                    cron_expression = '', 
                    enabled = True, ),
                untracked_files = immich_sdk.models.admin_config_integrity_job_dto.AdminConfigIntegrityJobDto(
                    cron_expression = '', 
                    enabled = True, ),
        )
        """

    def testAdminConfigIntegrityChecksDto(self):
        """Test AdminConfigIntegrityChecksDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
