# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.people_response_dto import PeopleResponseDto

class TestPeopleResponseDto(unittest.TestCase):
    """PeopleResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PeopleResponseDto:
        """Test PeopleResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PeopleResponseDto`
        """
        model = PeopleResponseDto()
        if include_optional:
            return PeopleResponseDto(
                has_next_page = True,
                hidden = 0,
                people = [
                    immich_sdk.models.person_response_dto.PersonResponseDto(
                        birth_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        color = '', 
                        id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                        is_favorite = True, 
                        is_hidden = True, 
                        name = '', 
                        thumbnail_path = '', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                total = 0
            )
        else:
            return PeopleResponseDto(
                hidden = 0,
                people = [
                    immich_sdk.models.person_response_dto.PersonResponseDto(
                        birth_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        color = '', 
                        id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                        is_favorite = True, 
                        is_hidden = True, 
                        name = '', 
                        thumbnail_path = '', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                total = 0,
        )
        """

    def testPeopleResponseDto(self):
        """Test PeopleResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
