# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.server_apk_links_dto import ServerApkLinksDto

class TestServerApkLinksDto(unittest.TestCase):
    """ServerApkLinksDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServerApkLinksDto:
        """Test ServerApkLinksDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServerApkLinksDto`
        """
        model = ServerApkLinksDto()
        if include_optional:
            return ServerApkLinksDto(
                arm64v8a = '',
                armeabiv7a = '',
                universal = '',
                x86_64 = ''
            )
        else:
            return ServerApkLinksDto(
                arm64v8a = '',
                armeabiv7a = '',
                universal = '',
                x86_64 = '',
        )
        """

    def testServerApkLinksDto(self):
        """Test ServerApkLinksDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
