# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.shared_link_edit_dto import SharedLinkEditDto

class TestSharedLinkEditDto(unittest.TestCase):
    """SharedLinkEditDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SharedLinkEditDto:
        """Test SharedLinkEditDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SharedLinkEditDto`
        """
        model = SharedLinkEditDto()
        if include_optional:
            return SharedLinkEditDto(
                allow_download = True,
                allow_upload = True,
                description = '',
                expires_at = '2024-01-01T00:00Z',
                password = '',
                show_metadata = True,
                slug = ''
            )
        else:
            return SharedLinkEditDto(
        )
        """

    def testSharedLinkEditDto(self):
        """Test SharedLinkEditDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
