# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.cluster_groups_api import ClusterGroupsApi


class TestClusterGroupsApi(unittest.TestCase):
    """ClusterGroupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ClusterGroupsApi()

    def tearDown(self) -> None:
        pass

    def test_accept_cluster_group_request(self) -> None:
        """Test case for accept_cluster_group_request

        Accept a cluster group request
        """
        pass

    def test_cluster_group_regenerate_people(self) -> None:
        """Test case for cluster_group_regenerate_people

        Regenerate people of users in cluster group
        """
        pass

    def test_create_cluster_group_request(self) -> None:
        """Test case for create_cluster_group_request

        Create a cluster group request
        """
        pass

    def test_delete_cluster_group_request(self) -> None:
        """Test case for delete_cluster_group_request

        Decline a cluster group request
        """
        pass

    def test_get_cluster_group_requests(self) -> None:
        """Test case for get_cluster_group_requests

        Retrieve cluster group requests
        """
        pass

    def test_get_cluster_group_requests_for_group(self) -> None:
        """Test case for get_cluster_group_requests_for_group

        Retrieve the requests sent by a cluster group
        """
        pass

    def test_get_cluster_group_users(self) -> None:
        """Test case for get_cluster_group_users

        Retrieve the users of a cluster group
        """
        pass

    def test_leave_cluster_group(self) -> None:
        """Test case for leave_cluster_group

        Leave a cluster group
        """
        pass


if __name__ == '__main__':
    unittest.main()
