# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.admin_config_notifications_dto import AdminConfigNotificationsDto

class TestAdminConfigNotificationsDto(unittest.TestCase):
    """AdminConfigNotificationsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminConfigNotificationsDto:
        """Test AdminConfigNotificationsDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminConfigNotificationsDto`
        """
        model = AdminConfigNotificationsDto()
        if include_optional:
            return AdminConfigNotificationsDto(
                smtp = immich_sdk.models.admin_config_smtp_dto.AdminConfigSmtpDto(
                    enabled = True, 
                    from = '', 
                    reply_to = '', 
                    transport = immich_sdk.models.admin_config_smtp_transport_dto.AdminConfigSmtpTransportDto(
                        host = '', 
                        ignore_cert = True, 
                        password = '', 
                        port = 0, 
                        secure = True, 
                        username = '', ), )
            )
        else:
            return AdminConfigNotificationsDto(
                smtp = immich_sdk.models.admin_config_smtp_dto.AdminConfigSmtpDto(
                    enabled = True, 
                    from = '', 
                    reply_to = '', 
                    transport = immich_sdk.models.admin_config_smtp_transport_dto.AdminConfigSmtpTransportDto(
                        host = '', 
                        ignore_cert = True, 
                        password = '', 
                        port = 0, 
                        secure = True, 
                        username = '', ), ),
        )
        """

    def testAdminConfigNotificationsDto(self):
        """Test AdminConfigNotificationsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
