# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.admin_config_library_dto import AdminConfigLibraryDto

class TestAdminConfigLibraryDto(unittest.TestCase):
    """AdminConfigLibraryDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminConfigLibraryDto:
        """Test AdminConfigLibraryDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminConfigLibraryDto`
        """
        model = AdminConfigLibraryDto()
        if include_optional:
            return AdminConfigLibraryDto(
                scan = immich_sdk.models.admin_config_library_scan_dto.AdminConfigLibraryScanDto(
                    cron_expression = '', 
                    enabled = True, ),
                watch = immich_sdk.models.admin_config_library_watch_dto.AdminConfigLibraryWatchDto(
                    enabled = True, )
            )
        else:
            return AdminConfigLibraryDto(
                scan = immich_sdk.models.admin_config_library_scan_dto.AdminConfigLibraryScanDto(
                    cron_expression = '', 
                    enabled = True, ),
                watch = immich_sdk.models.admin_config_library_watch_dto.AdminConfigLibraryWatchDto(
                    enabled = True, ),
        )
        """

    def testAdminConfigLibraryDto(self):
        """Test AdminConfigLibraryDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
