# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.workflow_share_response_dto import WorkflowShareResponseDto

class TestWorkflowShareResponseDto(unittest.TestCase):
    """WorkflowShareResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowShareResponseDto:
        """Test WorkflowShareResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowShareResponseDto`
        """
        model = WorkflowShareResponseDto()
        if include_optional:
            return WorkflowShareResponseDto(
                description = '',
                name = '',
                steps = [
                    immich_sdk.models.workflow_share_step_dto.WorkflowShareStepDto(
                        config = {
                            'key' : null
                            }, 
                        enabled = True, 
                        method = '', )
                    ],
                trigger = 'AssetCreate'
            )
        else:
            return WorkflowShareResponseDto(
                description = '',
                name = '',
                steps = [
                    immich_sdk.models.workflow_share_step_dto.WorkflowShareStepDto(
                        config = {
                            'key' : null
                            }, 
                        enabled = True, 
                        method = '', )
                    ],
                trigger = 'AssetCreate',
        )
        """

    def testWorkflowShareResponseDto(self):
        """Test WorkflowShareResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
