# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.asset_edits_response_dto import AssetEditsResponseDto

class TestAssetEditsResponseDto(unittest.TestCase):
    """AssetEditsResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssetEditsResponseDto:
        """Test AssetEditsResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssetEditsResponseDto`
        """
        model = AssetEditsResponseDto()
        if include_optional:
            return AssetEditsResponseDto(
                asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                edits = [
                    immich_sdk.models.asset_edit_action_item_response_dto.AssetEditActionItemResponseDto(
                        action = 'crop', 
                        id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                        parameters = null, )
                    ]
            )
        else:
            return AssetEditsResponseDto(
                asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                edits = [
                    immich_sdk.models.asset_edit_action_item_response_dto.AssetEditActionItemResponseDto(
                        action = 'crop', 
                        id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                        parameters = null, )
                    ],
        )
        """

    def testAssetEditsResponseDto(self):
        """Test AssetEditsResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
