# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.shared_link_create_dto import SharedLinkCreateDto

class TestSharedLinkCreateDto(unittest.TestCase):
    """SharedLinkCreateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SharedLinkCreateDto:
        """Test SharedLinkCreateDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SharedLinkCreateDto`
        """
        model = SharedLinkCreateDto()
        if include_optional:
            return SharedLinkCreateDto(
                album_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                allow_download = True,
                allow_upload = True,
                asset_ids = [
                    '62ECB020-8429-430c-a01F-FCCfeEe150AC'
                    ],
                description = '',
                expires_at = '2024-01-01T00:00Z',
                password = '',
                show_metadata = True,
                slug = '',
                type = 'ALBUM'
            )
        else:
            return SharedLinkCreateDto(
                type = 'ALBUM',
        )
        """

    def testSharedLinkCreateDto(self):
        """Test SharedLinkCreateDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
