# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.user_config_server_dto import UserConfigServerDto

class TestUserConfigServerDto(unittest.TestCase):
    """UserConfigServerDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserConfigServerDto:
        """Test UserConfigServerDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserConfigServerDto`
        """
        model = UserConfigServerDto()
        if include_optional:
            return UserConfigServerDto(
                external_domain = '',
                login_page_message = '',
                public_users = True
            )
        else:
            return UserConfigServerDto(
                external_domain = '',
                login_page_message = '',
                public_users = True,
        )
        """

    def testUserConfigServerDto(self):
        """Test UserConfigServerDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
