# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.api_key_response_dto import ApiKeyResponseDto

class TestApiKeyResponseDto(unittest.TestCase):
    """ApiKeyResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiKeyResponseDto:
        """Test ApiKeyResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiKeyResponseDto`
        """
        model = ApiKeyResponseDto()
        if include_optional:
            return ApiKeyResponseDto(
                created_at = '2024-01-01T00:00Z',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                name = '',
                permissions = [
                    'all'
                    ],
                updated_at = '2024-01-01T00:00Z'
            )
        else:
            return ApiKeyResponseDto(
                created_at = '2024-01-01T00:00Z',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                name = '',
                permissions = [
                    'all'
                    ],
                updated_at = '2024-01-01T00:00Z',
        )
        """

    def testApiKeyResponseDto(self):
        """Test ApiKeyResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
