# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.sync_partner_v1 import SyncPartnerV1

class TestSyncPartnerV1(unittest.TestCase):
    """SyncPartnerV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncPartnerV1:
        """Test SyncPartnerV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncPartnerV1`
        """
        model = SyncPartnerV1()
        if include_optional:
            return SyncPartnerV1(
                in_timeline = True,
                shared_by_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                shared_with_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC'
            )
        else:
            return SyncPartnerV1(
                in_timeline = True,
                shared_by_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                shared_with_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
        )
        """

    def testSyncPartnerV1(self):
        """Test SyncPartnerV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
