# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.asset_face_create_dto import AssetFaceCreateDto

class TestAssetFaceCreateDto(unittest.TestCase):
    """AssetFaceCreateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssetFaceCreateDto:
        """Test AssetFaceCreateDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssetFaceCreateDto`
        """
        model = AssetFaceCreateDto()
        if include_optional:
            return AssetFaceCreateDto(
                asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                height = -9007199254740991,
                image_height = -9007199254740991,
                image_width = -9007199254740991,
                person_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                width = -9007199254740991,
                x = -9007199254740991,
                y = -9007199254740991
            )
        else:
            return AssetFaceCreateDto(
                asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                height = -9007199254740991,
                image_height = -9007199254740991,
                image_width = -9007199254740991,
                person_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                width = -9007199254740991,
                x = -9007199254740991,
                y = -9007199254740991,
        )
        """

    def testAssetFaceCreateDto(self):
        """Test AssetFaceCreateDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
