# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.release_event_v1 import ReleaseEventV1

class TestReleaseEventV1(unittest.TestCase):
    """ReleaseEventV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReleaseEventV1:
        """Test ReleaseEventV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReleaseEventV1`
        """
        model = ReleaseEventV1()
        if include_optional:
            return ReleaseEventV1(
                checked_at = '',
                is_available = True,
                release_version = immich_sdk.models.server_version_response_dto.ServerVersionResponseDto(
                    major = 0, 
                    minor = 0, 
                    patch = 0, 
                    prerelease = 0, ),
                server_version = immich_sdk.models.server_version_response_dto.ServerVersionResponseDto(
                    major = 0, 
                    minor = 0, 
                    patch = 0, 
                    prerelease = 0, ),
                type = 'major'
            )
        else:
            return ReleaseEventV1(
                checked_at = '',
                is_available = True,
                release_version = immich_sdk.models.server_version_response_dto.ServerVersionResponseDto(
                    major = 0, 
                    minor = 0, 
                    patch = 0, 
                    prerelease = 0, ),
                server_version = immich_sdk.models.server_version_response_dto.ServerVersionResponseDto(
                    major = 0, 
                    minor = 0, 
                    patch = 0, 
                    prerelease = 0, ),
                type = 'major',
        )
        """

    def testReleaseEventV1(self):
        """Test ReleaseEventV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
