# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.jobs_api import JobsApi


class TestJobsApi(unittest.TestCase):
    """JobsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = JobsApi()

    def tearDown(self) -> None:
        pass

    def test_create_job(self) -> None:
        """Test case for create_job

        Create a manual job
        """
        pass

    def test_get_queues_legacy(self) -> None:
        """Test case for get_queues_legacy

        Retrieve queue counts and status
        """
        pass

    def test_run_queue_command_legacy(self) -> None:
        """Test case for run_queue_command_legacy

        Run jobs
        """
        pass


if __name__ == '__main__':
    unittest.main()
