# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.user_config_dto import UserConfigDto

class TestUserConfigDto(unittest.TestCase):
    """UserConfigDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserConfigDto:
        """Test UserConfigDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserConfigDto`
        """
        model = UserConfigDto()
        if include_optional:
            return UserConfigDto(
                ffmpeg = immich_sdk.models.user_config_f_fmpeg_dto.UserConfigFFmpegDto(
                    realtime = immich_sdk.models.user_config_f_fmpeg_realtime_dto.UserConfigFFmpegRealtimeDto(
                        enabled = True, 
                        resolutions = [
                            480
                            ], 
                        video_codecs = [
                            'h264'
                            ], ), ),
                image = immich_sdk.models.user_config_image_dto.UserConfigImageDto(
                    fullsize = immich_sdk.models.user_config_generated_fullsize_image_dto.UserConfigGeneratedFullsizeImageDto(
                        enabled = True, ), 
                    preview = immich_sdk.models.user_config_generated_image_dto.UserConfigGeneratedImageDto(
                        size = 1, ), 
                    thumbnail = immich_sdk.models.user_config_generated_image_dto.UserConfigGeneratedImageDto(
                        size = 1, ), ),
                machine_learning = immich_sdk.models.user_config_machine_learning_dto.UserConfigMachineLearningDto(
                    clip = immich_sdk.models.user_config_clip_dto.UserConfigClipDto(
                        enabled = True, ), 
                    duplicate_detection = immich_sdk.models.user_config_duplicate_detection_dto.UserConfigDuplicateDetectionDto(
                        enabled = True, ), 
                    enabled = True, 
                    facial_recognition = immich_sdk.models.user_config_facial_recognition_dto.UserConfigFacialRecognitionDto(
                        enabled = True, 
                        min_faces = 1, ), 
                    ocr = immich_sdk.models.user_config_ocr_dto.UserConfigOcrDto(
                        enabled = True, ), ),
                map = immich_sdk.models.user_config_map_dto.UserConfigMapDto(
                    dark_style = '', 
                    enabled = True, 
                    light_style = '', ),
                oauth = immich_sdk.models.user_config_o_auth_dto.UserConfigOAuthDto(
                    auto_launch = True, 
                    button_text = '', 
                    enabled = True, ),
                password_login = immich_sdk.models.user_config_password_login_dto.UserConfigPasswordLoginDto(
                    enabled = True, ),
                reverse_geocoding = immich_sdk.models.user_config_reverse_geocoding_dto.UserConfigReverseGeocodingDto(
                    enabled = True, ),
                server = immich_sdk.models.user_config_server_dto.UserConfigServerDto(
                    external_domain = '', 
                    login_page_message = '', 
                    public_users = True, ),
                theme = immich_sdk.models.user_config_theme_dto.UserConfigThemeDto(
                    custom_css = '', ),
                trash = immich_sdk.models.user_config_trash_dto.UserConfigTrashDto(
                    days = 0, 
                    enabled = True, ),
                user = immich_sdk.models.user_config_user_dto.UserConfigUserDto(
                    delete_delay = 1, )
            )
        else:
            return UserConfigDto(
                ffmpeg = immich_sdk.models.user_config_f_fmpeg_dto.UserConfigFFmpegDto(
                    realtime = immich_sdk.models.user_config_f_fmpeg_realtime_dto.UserConfigFFmpegRealtimeDto(
                        enabled = True, 
                        resolutions = [
                            480
                            ], 
                        video_codecs = [
                            'h264'
                            ], ), ),
                image = immich_sdk.models.user_config_image_dto.UserConfigImageDto(
                    fullsize = immich_sdk.models.user_config_generated_fullsize_image_dto.UserConfigGeneratedFullsizeImageDto(
                        enabled = True, ), 
                    preview = immich_sdk.models.user_config_generated_image_dto.UserConfigGeneratedImageDto(
                        size = 1, ), 
                    thumbnail = immich_sdk.models.user_config_generated_image_dto.UserConfigGeneratedImageDto(
                        size = 1, ), ),
                machine_learning = immich_sdk.models.user_config_machine_learning_dto.UserConfigMachineLearningDto(
                    clip = immich_sdk.models.user_config_clip_dto.UserConfigClipDto(
                        enabled = True, ), 
                    duplicate_detection = immich_sdk.models.user_config_duplicate_detection_dto.UserConfigDuplicateDetectionDto(
                        enabled = True, ), 
                    enabled = True, 
                    facial_recognition = immich_sdk.models.user_config_facial_recognition_dto.UserConfigFacialRecognitionDto(
                        enabled = True, 
                        min_faces = 1, ), 
                    ocr = immich_sdk.models.user_config_ocr_dto.UserConfigOcrDto(
                        enabled = True, ), ),
                map = immich_sdk.models.user_config_map_dto.UserConfigMapDto(
                    dark_style = '', 
                    enabled = True, 
                    light_style = '', ),
                oauth = immich_sdk.models.user_config_o_auth_dto.UserConfigOAuthDto(
                    auto_launch = True, 
                    button_text = '', 
                    enabled = True, ),
                password_login = immich_sdk.models.user_config_password_login_dto.UserConfigPasswordLoginDto(
                    enabled = True, ),
                reverse_geocoding = immich_sdk.models.user_config_reverse_geocoding_dto.UserConfigReverseGeocodingDto(
                    enabled = True, ),
                server = immich_sdk.models.user_config_server_dto.UserConfigServerDto(
                    external_domain = '', 
                    login_page_message = '', 
                    public_users = True, ),
                theme = immich_sdk.models.user_config_theme_dto.UserConfigThemeDto(
                    custom_css = '', ),
                trash = immich_sdk.models.user_config_trash_dto.UserConfigTrashDto(
                    days = 0, 
                    enabled = True, ),
                user = immich_sdk.models.user_config_user_dto.UserConfigUserDto(
                    delete_delay = 1, ),
        )
        """

    def testUserConfigDto(self):
        """Test UserConfigDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
