# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.integrity_report_response_dto import IntegrityReportResponseDto

class TestIntegrityReportResponseDto(unittest.TestCase):
    """IntegrityReportResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IntegrityReportResponseDto:
        """Test IntegrityReportResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IntegrityReportResponseDto`
        """
        model = IntegrityReportResponseDto()
        if include_optional:
            return IntegrityReportResponseDto(
                items = [
                    immich_sdk.models.integrity_report_response_dto_items_inner.IntegrityReportResponseDto_items_inner(
                        id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                        path = '', 
                        type = 'untracked_file', )
                    ],
                next_cursor = ''
            )
        else:
            return IntegrityReportResponseDto(
                items = [
                    immich_sdk.models.integrity_report_response_dto_items_inner.IntegrityReportResponseDto_items_inner(
                        id = '62ECB020-8429-430c-a01F-FCCfeEe150AC', 
                        path = '', 
                        type = 'untracked_file', )
                    ],
        )
        """

    def testIntegrityReportResponseDto(self):
        """Test IntegrityReportResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
