# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.asset_copy_dto import AssetCopyDto

class TestAssetCopyDto(unittest.TestCase):
    """AssetCopyDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssetCopyDto:
        """Test AssetCopyDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssetCopyDto`
        """
        model = AssetCopyDto()
        if include_optional:
            return AssetCopyDto(
                albums = True,
                favorite = True,
                shared_links = True,
                sidecar = True,
                source_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                stack = True,
                target_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC'
            )
        else:
            return AssetCopyDto(
                source_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                target_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
        )
        """

    def testAssetCopyDto(self):
        """Test AssetCopyDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
