# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.user_preferences_update_dto import UserPreferencesUpdateDto

class TestUserPreferencesUpdateDto(unittest.TestCase):
    """UserPreferencesUpdateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserPreferencesUpdateDto:
        """Test UserPreferencesUpdateDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserPreferencesUpdateDto`
        """
        model = UserPreferencesUpdateDto()
        if include_optional:
            return UserPreferencesUpdateDto(
                albums = immich_sdk.models.albums_update.AlbumsUpdate(
                    default_asset_order = 'asc', ),
                avatar = immich_sdk.models.avatar_update.AvatarUpdate(
                    color = 'primary', ),
                cast = immich_sdk.models.cast_update.CastUpdate(
                    g_cast_enabled = True, ),
                download = immich_sdk.models.download_update.DownloadUpdate(
                    archive_size = 1, 
                    include_embedded_videos = True, ),
                email_notifications = immich_sdk.models.email_notifications_update.EmailNotificationsUpdate(
                    album_invite = True, 
                    album_update = True, 
                    enabled = True, ),
                folders = immich_sdk.models.folders_update.FoldersUpdate(
                    enabled = True, 
                    sidebar_web = True, ),
                memories = immich_sdk.models.memories_update.MemoriesUpdate(
                    duration = 1, 
                    enabled = True, 
                    sidebar_web = True, ),
                people = immich_sdk.models.people_update.PeopleUpdate(
                    enabled = True, 
                    minimum_faces = 1, 
                    sidebar_web = True, ),
                purchase = immich_sdk.models.purchase_update.PurchaseUpdate(
                    hide_buy_button_until = '', 
                    show_support_badge = True, ),
                ratings = immich_sdk.models.ratings_update.RatingsUpdate(
                    enabled = True, ),
                recently_added = immich_sdk.models.recently_added_update.RecentlyAddedUpdate(
                    sidebar_web = True, ),
                shared_links = immich_sdk.models.shared_links_update.SharedLinksUpdate(
                    enabled = True, 
                    sidebar_web = True, ),
                tags = immich_sdk.models.tags_update.TagsUpdate(
                    enabled = True, 
                    sidebar_web = True, )
            )
        else:
            return UserPreferencesUpdateDto(
        )
        """

    def testUserPreferencesUpdateDto(self):
        """Test UserPreferencesUpdateDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
