# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.asset_stats_response_dto import AssetStatsResponseDto

class TestAssetStatsResponseDto(unittest.TestCase):
    """AssetStatsResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssetStatsResponseDto:
        """Test AssetStatsResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssetStatsResponseDto`
        """
        model = AssetStatsResponseDto()
        if include_optional:
            return AssetStatsResponseDto(
                images = -9007199254740991,
                total = -9007199254740991,
                videos = -9007199254740991
            )
        else:
            return AssetStatsResponseDto(
                images = -9007199254740991,
                total = -9007199254740991,
                videos = -9007199254740991,
        )
        """

    def testAssetStatsResponseDto(self):
        """Test AssetStatsResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
