# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.admin_config_logging_dto import AdminConfigLoggingDto

class TestAdminConfigLoggingDto(unittest.TestCase):
    """AdminConfigLoggingDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminConfigLoggingDto:
        """Test AdminConfigLoggingDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminConfigLoggingDto`
        """
        model = AdminConfigLoggingDto()
        if include_optional:
            return AdminConfigLoggingDto(
                enabled = True,
                level = 'verbose'
            )
        else:
            return AdminConfigLoggingDto(
                enabled = True,
                level = 'verbose',
        )
        """

    def testAdminConfigLoggingDto(self):
        """Test AdminConfigLoggingDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
