# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.usage_by_user_dto import UsageByUserDto

class TestUsageByUserDto(unittest.TestCase):
    """UsageByUserDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsageByUserDto:
        """Test UsageByUserDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsageByUserDto`
        """
        model = UsageByUserDto()
        if include_optional:
            return UsageByUserDto(
                photos = -9007199254740991,
                quota_size_in_bytes = -9007199254740991,
                usage = -9007199254740991,
                usage_photos = -9007199254740991,
                usage_videos = -9007199254740991,
                user_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                user_name = '',
                videos = -9007199254740991
            )
        else:
            return UsageByUserDto(
                photos = -9007199254740991,
                quota_size_in_bytes = -9007199254740991,
                usage = -9007199254740991,
                usage_photos = -9007199254740991,
                usage_videos = -9007199254740991,
                user_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                user_name = '',
                videos = -9007199254740991,
        )
        """

    def testUsageByUserDto(self):
        """Test UsageByUserDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
