# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.download_api import DownloadApi


class TestDownloadApi(unittest.TestCase):
    """DownloadApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DownloadApi()

    def tearDown(self) -> None:
        pass

    def test_download_archive(self) -> None:
        """Test case for download_archive

        Download asset archive
        """
        pass

    def test_get_download_info(self) -> None:
        """Test case for get_download_info

        Retrieve download information
        """
        pass


if __name__ == '__main__':
    unittest.main()
