# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.config_public_api import ConfigPublicApi


class TestConfigPublicApi(unittest.TestCase):
    """ConfigPublicApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConfigPublicApi()

    def tearDown(self) -> None:
        pass

    def test_get_public_config(self) -> None:
        """Test case for get_public_config

        Get the public configuration
        """
        pass

    def test_get_public_config_defaults(self) -> None:
        """Test case for get_public_config_defaults

        Get the public configuration defaults
        """
        pass


if __name__ == '__main__':
    unittest.main()
