# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.user_config_f_fmpeg_realtime_dto import UserConfigFFmpegRealtimeDto

class TestUserConfigFFmpegRealtimeDto(unittest.TestCase):
    """UserConfigFFmpegRealtimeDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserConfigFFmpegRealtimeDto:
        """Test UserConfigFFmpegRealtimeDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserConfigFFmpegRealtimeDto`
        """
        model = UserConfigFFmpegRealtimeDto()
        if include_optional:
            return UserConfigFFmpegRealtimeDto(
                enabled = True,
                resolutions = [
                    480
                    ],
                video_codecs = [
                    'h264'
                    ]
            )
        else:
            return UserConfigFFmpegRealtimeDto(
                enabled = True,
                resolutions = [
                    480
                    ],
                video_codecs = [
                    'h264'
                    ],
        )
        """

    def testUserConfigFFmpegRealtimeDto(self):
        """Test UserConfigFFmpegRealtimeDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
