# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.transcode_policy import TranscodePolicy

class TestTranscodePolicy(unittest.TestCase):
    """TranscodePolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTranscodePolicy(self):
        """Test TranscodePolicy"""
        # inst = TranscodePolicy()

if __name__ == '__main__':
    unittest.main()
