# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.sync_asset_exif_v1 import SyncAssetExifV1

class TestSyncAssetExifV1(unittest.TestCase):
    """SyncAssetExifV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncAssetExifV1:
        """Test SyncAssetExifV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncAssetExifV1`
        """
        model = SyncAssetExifV1()
        if include_optional:
            return SyncAssetExifV1(
                asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                city = '',
                country = '',
                date_time_original = '2024-01-01T00:00Z',
                description = '',
                exif_image_height = -9007199254740991,
                exif_image_width = -9007199254740991,
                exposure_time = '',
                f_number = 1.337,
                file_size_in_byte = -9007199254740991,
                focal_length = 1.337,
                fps = 1.337,
                iso = -9007199254740991,
                latitude = 1.337,
                lens_model = '',
                longitude = 1.337,
                make = '',
                model = '',
                modify_date = '2024-01-01T00:00Z',
                orientation = '',
                profile_description = '',
                projection_type = '',
                rating = -9007199254740991,
                state = '',
                time_zone = ''
            )
        else:
            return SyncAssetExifV1(
                asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                city = '',
                country = '',
                date_time_original = '2024-01-01T00:00Z',
                description = '',
                exif_image_height = -9007199254740991,
                exif_image_width = -9007199254740991,
                exposure_time = '',
                f_number = 1.337,
                file_size_in_byte = -9007199254740991,
                focal_length = 1.337,
                fps = 1.337,
                iso = -9007199254740991,
                latitude = 1.337,
                lens_model = '',
                longitude = 1.337,
                make = '',
                model = '',
                modify_date = '2024-01-01T00:00Z',
                orientation = '',
                profile_description = '',
                projection_type = '',
                rating = -9007199254740991,
                state = '',
                time_zone = '',
        )
        """

    def testSyncAssetExifV1(self):
        """Test SyncAssetExifV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
