# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.asset_edits_create_dto import AssetEditsCreateDto

class TestAssetEditsCreateDto(unittest.TestCase):
    """AssetEditsCreateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssetEditsCreateDto:
        """Test AssetEditsCreateDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssetEditsCreateDto`
        """
        model = AssetEditsCreateDto()
        if include_optional:
            return AssetEditsCreateDto(
                edits = [
                    immich_sdk.models.asset_edit_action_item_dto.AssetEditActionItemDto(
                        action = 'crop', 
                        parameters = null, )
                    ]
            )
        else:
            return AssetEditsCreateDto(
                edits = [
                    immich_sdk.models.asset_edit_action_item_dto.AssetEditActionItemDto(
                        action = 'crop', 
                        parameters = null, )
                    ],
        )
        """

    def testAssetEditsCreateDto(self):
        """Test AssetEditsCreateDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
