# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.views_api import ViewsApi


class TestViewsApi(unittest.TestCase):
    """ViewsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ViewsApi()

    def tearDown(self) -> None:
        pass

    def test_get_assets_by_original_path(self) -> None:
        """Test case for get_assets_by_original_path

        Retrieve assets by original path
        """
        pass

    def test_get_unique_original_paths(self) -> None:
        """Test case for get_unique_original_paths

        Retrieve unique paths
        """
        pass


if __name__ == '__main__':
    unittest.main()
