# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.notification_dto import NotificationDto

class TestNotificationDto(unittest.TestCase):
    """NotificationDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotificationDto:
        """Test NotificationDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NotificationDto`
        """
        model = NotificationDto()
        if include_optional:
            return NotificationDto(
                created_at = '2024-01-01T00:00Z',
                data = {
                    'key' : null
                    },
                description = '',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                level = 'success',
                read_at = '2024-01-01T00:00Z',
                title = '',
                type = 'JobFailed'
            )
        else:
            return NotificationDto(
                created_at = '2024-01-01T00:00Z',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                level = 'success',
                title = '',
                type = 'JobFailed',
        )
        """

    def testNotificationDto(self):
        """Test NotificationDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
