# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.integrity_report_summary_response_dto import IntegrityReportSummaryResponseDto

class TestIntegrityReportSummaryResponseDto(unittest.TestCase):
    """IntegrityReportSummaryResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IntegrityReportSummaryResponseDto:
        """Test IntegrityReportSummaryResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IntegrityReportSummaryResponseDto`
        """
        model = IntegrityReportSummaryResponseDto()
        if include_optional:
            return IntegrityReportSummaryResponseDto(
                checksum_mismatch = 0,
                missing_file = 0,
                untracked_file = 0
            )
        else:
            return IntegrityReportSummaryResponseDto(
                checksum_mismatch = 0,
                missing_file = 0,
                untracked_file = 0,
        )
        """

    def testIntegrityReportSummaryResponseDto(self):
        """Test IntegrityReportSummaryResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
