# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.admin_config_nightly_tasks_dto import AdminConfigNightlyTasksDto

class TestAdminConfigNightlyTasksDto(unittest.TestCase):
    """AdminConfigNightlyTasksDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminConfigNightlyTasksDto:
        """Test AdminConfigNightlyTasksDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminConfigNightlyTasksDto`
        """
        model = AdminConfigNightlyTasksDto()
        if include_optional:
            return AdminConfigNightlyTasksDto(
                cluster_new_faces = True,
                database_cleanup = True,
                generate_memories = True,
                missing_thumbnails = True,
                start_time = '23:20',
                sync_quota_usage = True
            )
        else:
            return AdminConfigNightlyTasksDto(
                cluster_new_faces = True,
                database_cleanup = True,
                generate_memories = True,
                missing_thumbnails = True,
                start_time = '23:20',
                sync_quota_usage = True,
        )
        """

    def testAdminConfigNightlyTasksDto(self):
        """Test AdminConfigNightlyTasksDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
