# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.queues_api import QueuesApi


class TestQueuesApi(unittest.TestCase):
    """QueuesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QueuesApi()

    def tearDown(self) -> None:
        pass

    def test_empty_queue(self) -> None:
        """Test case for empty_queue

        Empty a queue
        """
        pass

    def test_get_queue(self) -> None:
        """Test case for get_queue

        Retrieve a queue
        """
        pass

    def test_get_queue_jobs(self) -> None:
        """Test case for get_queue_jobs

        Retrieve queue jobs
        """
        pass

    def test_get_queues(self) -> None:
        """Test case for get_queues

        List all queues
        """
        pass

    def test_update_queue(self) -> None:
        """Test case for update_queue

        Update a queue
        """
        pass


if __name__ == '__main__':
    unittest.main()
