# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.people_update_item import PeopleUpdateItem

class TestPeopleUpdateItem(unittest.TestCase):
    """PeopleUpdateItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PeopleUpdateItem:
        """Test PeopleUpdateItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PeopleUpdateItem`
        """
        model = PeopleUpdateItem()
        if include_optional:
            return PeopleUpdateItem(
                birth_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                color = '#ECB02084',
                feature_face_asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                is_favorite = True,
                is_hidden = True,
                name = ''
            )
        else:
            return PeopleUpdateItem(
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
        )
        """

    def testPeopleUpdateItem(self):
        """Test PeopleUpdateItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
