# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.sync_asset_edit_v1 import SyncAssetEditV1

class TestSyncAssetEditV1(unittest.TestCase):
    """SyncAssetEditV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncAssetEditV1:
        """Test SyncAssetEditV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncAssetEditV1`
        """
        model = SyncAssetEditV1()
        if include_optional:
            return SyncAssetEditV1(
                action = 'crop',
                asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                parameters = {
                    'key' : null
                    },
                sequence = -9007199254740991
            )
        else:
            return SyncAssetEditV1(
                action = 'crop',
                asset_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                parameters = {
                    'key' : null
                    },
                sequence = -9007199254740991,
        )
        """

    def testSyncAssetEditV1(self):
        """Test SyncAssetEditV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
