# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.server_version_history_response_dto import ServerVersionHistoryResponseDto

class TestServerVersionHistoryResponseDto(unittest.TestCase):
    """ServerVersionHistoryResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServerVersionHistoryResponseDto:
        """Test ServerVersionHistoryResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServerVersionHistoryResponseDto`
        """
        model = ServerVersionHistoryResponseDto()
        if include_optional:
            return ServerVersionHistoryResponseDto(
                created_at = '2024-01-01T00:00Z',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                version = ''
            )
        else:
            return ServerVersionHistoryResponseDto(
                created_at = '2024-01-01T00:00Z',
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                version = '',
        )
        """

    def testServerVersionHistoryResponseDto(self):
        """Test ServerVersionHistoryResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
