# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.ids_filter import IdsFilter

class TestIdsFilter(unittest.TestCase):
    """IdsFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdsFilter:
        """Test IdsFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IdsFilter`
        """
        model = IdsFilter()
        if include_optional:
            return IdsFilter(
                all = [
                    '62ECB020-8429-430c-a01F-FCCfeEe150AC'
                    ],
                any = [
                    '62ECB020-8429-430c-a01F-FCCfeEe150AC'
                    ],
                var_none = [
                    '62ECB020-8429-430c-a01F-FCCfeEe150AC'
                    ]
            )
        else:
            return IdsFilter(
        )
        """

    def testIdsFilter(self):
        """Test IdsFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
