# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.storage_folder import StorageFolder

class TestStorageFolder(unittest.TestCase):
    """StorageFolder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorageFolder(self):
        """Test StorageFolder"""
        # inst = StorageFolder()

if __name__ == '__main__':
    unittest.main()
