# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.activities_api import ActivitiesApi


class TestActivitiesApi(unittest.TestCase):
    """ActivitiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ActivitiesApi()

    def tearDown(self) -> None:
        pass

    def test_create_activity(self) -> None:
        """Test case for create_activity

        Create an activity
        """
        pass

    def test_delete_activity(self) -> None:
        """Test case for delete_activity

        Delete an activity
        """
        pass

    def test_get_activities(self) -> None:
        """Test case for get_activities

        List all activities
        """
        pass

    def test_get_activity_statistics(self) -> None:
        """Test case for get_activity_statistics

        Retrieve activity statistics
        """
        pass


if __name__ == '__main__':
    unittest.main()
