# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.admin_config_ocr_dto import AdminConfigOcrDto

class TestAdminConfigOcrDto(unittest.TestCase):
    """AdminConfigOcrDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminConfigOcrDto:
        """Test AdminConfigOcrDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminConfigOcrDto`
        """
        model = AdminConfigOcrDto()
        if include_optional:
            return AdminConfigOcrDto(
                enabled = True,
                max_resolution = 1,
                min_detection_score = 0.1,
                min_recognition_score = 0.1,
                model_name = ''
            )
        else:
            return AdminConfigOcrDto(
                enabled = True,
                max_resolution = 1,
                min_detection_score = 0.1,
                min_recognition_score = 0.1,
                model_name = '',
        )
        """

    def testAdminConfigOcrDto(self):
        """Test AdminConfigOcrDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
