# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.number_filter import NumberFilter

class TestNumberFilter(unittest.TestCase):
    """NumberFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NumberFilter:
        """Test NumberFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NumberFilter`
        """
        model = NumberFilter()
        if include_optional:
            return NumberFilter(
                eq = 1.337,
                gt = 1.337,
                gte = 1.337,
                var_in = [
                    1.337
                    ],
                lt = 1.337,
                lte = 1.337,
                ne = 1.337,
                not_in = [
                    1.337
                    ]
            )
        else:
            return NumberFilter(
        )
        """

    def testNumberFilter(self):
        """Test NumberFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
