# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.asset_bulk_update_dto import AssetBulkUpdateDto

class TestAssetBulkUpdateDto(unittest.TestCase):
    """AssetBulkUpdateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssetBulkUpdateDto:
        """Test AssetBulkUpdateDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssetBulkUpdateDto`
        """
        model = AssetBulkUpdateDto()
        if include_optional:
            return AssetBulkUpdateDto(
                date_time_original = '',
                date_time_relative = -9007199254740991,
                description = '',
                duplicate_id = '',
                ids = [
                    '62ECB020-8429-430c-a01F-FCCfeEe150AC'
                    ],
                is_favorite = True,
                latitude = -90,
                longitude = -180,
                rating = -1,
                time_zone = '',
                visibility = 'archive'
            )
        else:
            return AssetBulkUpdateDto(
                ids = [
                    '62ECB020-8429-430c-a01F-FCCfeEe150AC'
                    ],
        )
        """

    def testAssetBulkUpdateDto(self):
        """Test AssetBulkUpdateDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
