# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_create_profile_image(self) -> None:
        """Test case for create_profile_image

        Create user profile image
        """
        pass

    def test_delete_profile_image(self) -> None:
        """Test case for delete_profile_image

        Delete user profile image
        """
        pass

    def test_delete_user_license(self) -> None:
        """Test case for delete_user_license

        Delete user product key
        """
        pass

    def test_delete_user_onboarding(self) -> None:
        """Test case for delete_user_onboarding

        Delete user onboarding
        """
        pass

    def test_get_my_calendar_heatmap(self) -> None:
        """Test case for get_my_calendar_heatmap

        Retrieve calendar heatmap activity
        """
        pass

    def test_get_my_preferences(self) -> None:
        """Test case for get_my_preferences

        Get my preferences
        """
        pass

    def test_get_my_user(self) -> None:
        """Test case for get_my_user

        Get current user
        """
        pass

    def test_get_profile_image(self) -> None:
        """Test case for get_profile_image

        Retrieve user profile image
        """
        pass

    def test_get_user(self) -> None:
        """Test case for get_user

        Retrieve a user
        """
        pass

    def test_get_user_license(self) -> None:
        """Test case for get_user_license

        Retrieve user product key
        """
        pass

    def test_get_user_onboarding(self) -> None:
        """Test case for get_user_onboarding

        Retrieve user onboarding
        """
        pass

    def test_search_users(self) -> None:
        """Test case for search_users

        Get all users
        """
        pass

    def test_set_user_license(self) -> None:
        """Test case for set_user_license

        Set user product key
        """
        pass

    def test_set_user_onboarding(self) -> None:
        """Test case for set_user_onboarding

        Update user onboarding
        """
        pass

    def test_update_my_preferences(self) -> None:
        """Test case for update_my_preferences

        Update my preferences
        """
        pass

    def test_update_my_user(self) -> None:
        """Test case for update_my_user

        Update current user
        """
        pass


if __name__ == '__main__':
    unittest.main()
