# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.queue_response_dto import QueueResponseDto

class TestQueueResponseDto(unittest.TestCase):
    """QueueResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueueResponseDto:
        """Test QueueResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueueResponseDto`
        """
        model = QueueResponseDto()
        if include_optional:
            return QueueResponseDto(
                is_paused = True,
                name = 'thumbnailGeneration',
                statistics = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                    active = -9007199254740991, 
                    completed = -9007199254740991, 
                    delayed = -9007199254740991, 
                    failed = -9007199254740991, 
                    paused = -9007199254740991, 
                    waiting = -9007199254740991, )
            )
        else:
            return QueueResponseDto(
                is_paused = True,
                name = 'thumbnailGeneration',
                statistics = immich_sdk.models.queue_statistics_dto.QueueStatisticsDto(
                    active = -9007199254740991, 
                    completed = -9007199254740991, 
                    delayed = -9007199254740991, 
                    failed = -9007199254740991, 
                    paused = -9007199254740991, 
                    waiting = -9007199254740991, ),
        )
        """

    def testQueueResponseDto(self):
        """Test QueueResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
