# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.api.config_admin_api import ConfigAdminApi


class TestConfigAdminApi(unittest.TestCase):
    """ConfigAdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConfigAdminApi()

    def tearDown(self) -> None:
        pass

    def test_get_admin_config(self) -> None:
        """Test case for get_admin_config

        Get the admin configuration
        """
        pass

    def test_get_admin_config_defaults(self) -> None:
        """Test case for get_admin_config_defaults

        Get the system configuration defaults
        """
        pass

    def test_update_admin_config(self) -> None:
        """Test case for update_admin_config

        Update the system configuration
        """
        pass


if __name__ == '__main__':
    unittest.main()
