# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.tag_create_dto import TagCreateDto

class TestTagCreateDto(unittest.TestCase):
    """TagCreateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TagCreateDto:
        """Test TagCreateDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TagCreateDto`
        """
        model = TagCreateDto()
        if include_optional:
            return TagCreateDto(
                color = '#ECB02084',
                name = 'k$?x u&K}qz^sEC(lJ)=,j',
                parent_id = '62ECB020-8429-430c-a01F-FCCfeEe150AC'
            )
        else:
            return TagCreateDto(
                name = 'k$?x u&K}qz^sEC(lJ)=,j',
        )
        """

    def testTagCreateDto(self):
        """Test TagCreateDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
