# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.recently_added_update import RecentlyAddedUpdate

class TestRecentlyAddedUpdate(unittest.TestCase):
    """RecentlyAddedUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecentlyAddedUpdate:
        """Test RecentlyAddedUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecentlyAddedUpdate`
        """
        model = RecentlyAddedUpdate()
        if include_optional:
            return RecentlyAddedUpdate(
                sidebar_web = True
            )
        else:
            return RecentlyAddedUpdate(
        )
        """

    def testRecentlyAddedUpdate(self):
        """Test RecentlyAddedUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
