# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 3.2.0-rc.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_sdk.models.workflow_response_dto import WorkflowResponseDto

class TestWorkflowResponseDto(unittest.TestCase):
    """WorkflowResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowResponseDto:
        """Test WorkflowResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowResponseDto`
        """
        model = WorkflowResponseDto()
        if include_optional:
            return WorkflowResponseDto(
                created_at = '',
                description = '',
                enabled = True,
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                logging = True,
                name = '',
                steps = [
                    immich_sdk.models.workflow_step_dto.WorkflowStepDto(
                        config = {
                            'key' : null
                            }, 
                        enabled = True, 
                        method = '', )
                    ],
                trigger = 'AssetCreate',
                updated_at = ''
            )
        else:
            return WorkflowResponseDto(
                created_at = '',
                description = '',
                enabled = True,
                id = '62ECB020-8429-430c-a01F-FCCfeEe150AC',
                logging = True,
                name = '',
                steps = [
                    immich_sdk.models.workflow_step_dto.WorkflowStepDto(
                        config = {
                            'key' : null
                            }, 
                        enabled = True, 
                        method = '', )
                    ],
                trigger = 'AssetCreate',
                updated_at = '',
        )
        """

    def testWorkflowResponseDto(self):
        """Test WorkflowResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
